### ISSUE TITLE
[base_contact]  'pop' not supported on frozendict on _basecontact_check_context

### ISSUE THREAD

**Issue by TheCloneMaster** [OCA/partner-contact#1]
In latest 8.0 branch, there was a change on how context is handled, as now it is a frozendict, so context.pop() raises 

```
  'pop' not supported on frozendict on _basecontact_check_context
```

Just add 

```
    context = dict(context or {})
```

at the beginning of _basecontact_check_context to fix it...

Anyway, seems like a standard procedure to do that whenever context.pop() is required, so it helps to other versions besides 8.0...

Still learning git, so I am not sure how to create the MP (or whatever it is called now on git)...

**Comment by bwrsandman** [comment]
> ```
>     context = dict(context or {})
> ```

Yet another, creative way of doing

```
if context is None:
    context = {}
```

What is that, now 5 different variations? :wink: 

In all seriousness @TheCloneMaster, you can edit directly from the github page if you want, it will create the Pull Request, fork and branch automatically for you.

I assume [this is the line you want to edit](https://github.com/OCA/partner-contact/edit/master/base_contact/base_contact.py#L62)

**Comment by bwrsandman** [comment]
I wonder if this problem could be avoided using the new api

**Comment by TheCloneMaster** [comment]
Hi Sandy,

Not the same, as dict() returns a copy.

It seems like OpenERP S.A. has changed some internals about context, and
now it is received as a frozendict, and hence it doesn't allow to "pop"
from it...

The code as it was has been working perfectly from v7.0 up to saas-5.
 Somewhere between saas-5 and 8.0, something changed context to a
frozendict...

If you try to pop from None, the error is different...
      AttributeError: 'NoneType' object has no attribute 'pop'

I will try the direct edit, thanks for letting me know.  I am definitely
still lost at git, but with your help that will improve soon...

Regards,
-Mario

**Comment by pedrobaeza** [comment]
This is probably due to the new API, that was merged recently. Maybe there is a good reason not to allow to remove elements from the context. Better pass a copy of the context without the element to the method that requires this change of the dictionary.

Regards.

**Comment by guewen** [comment]
The usage of a frozendict for the context is a good change. It prevents to
alter the context and thus prevents some side effects.

Actually, it is already (before the new api) a good practice to make a copy
of the context before altering it. Why? Let's consider this case:

```
class sale_order(...):
    ...
    def run(self, cr, uid, ids, context=None):
        if context is None:
            context = {}
        context['key'] = 1
        self.m1(cr, uid, ids, context=context)
        self.m2(cr, uid, ids, context=context)

    def m1(self, cr, uid, ids, context=None):
        if context is None:
            context = {}
        context.pop('key')

    def m2(self, cr, uid, ids, context=None):
        if context is None:
            context = {}
        assert context.get('key')
```

The assert in m2 will fail of course, but should not have. This example is
simplified as extreme, but cases as this one could happen in a long chain
of calls. Changes made on the context should not be propagated upstream, so
having an immutable context forces to make a copy and avoid this situation.

Note on the dict(context or {}): this is slower than:

```
if context is None:
    context = {}
else:
    context = context.copy()
```

Also, it will make a new dict if context is an empty dict.

**Comment by TheCloneMaster** [comment]
Besides, calls to _basecontact_check_context never use  mode='search', so
we ca just remove this method and replace

```
    context = self._basecontact_check_context(cr, user, 'create',
```

context)

with
        context = dict(context or {})
        context.pop('search_show_all_positions', None)

in the four lines that call it, and avoid the overhead of calling another
method...

We will only miss the explanation about why this is needed for non search
cases... Or that comment could be keept...

What do you think?  Is that change worth it  ?

**Comment by bwrsandman** [comment]
`context = dict(context or {})` seems to be the proper way of doing it.

**Comment by NL66278** [comment]
Module base_contact was deprecated and replaced in 8.0
