### ISSUE TITLE
[v10] partner_firstname and double name

### ISSUE THREAD

**Issue by Troublicious** [OCA/partner-contact#1011]
Hello everyone, there is a problem (at least in version 10) with the partner_firstname module:
Indeed, when creating a contact with a double name for lastname, the module records the right information in the right places. However, in case of modification of the lastname or the firstname of the contact, the double name is incorrectly saved, and the second part of the lastname is recorded with the firstname!

When **creating** a double name contact everything is correct:
Lastname : De Gaulle
Firstname : Pierre
This is ok.

But when **modifying** a double name contact, after saving we have this :
Lastname : De
Firstname : Gaulle Charles

And what is expected :
Lastname : De Gaulle
Firstname : Charles

I only tested this on V10.

**Comment by NL66278** [comment]
At the moment there are multiple modules that split the monolithic res.partner name field into multiple parts. The original one was partner_firstname, but there is also partner_second_lastname and l10n_nl_partner_name in the Dutch localization that adds a middlename (infix) and initials.

There is an attempt to modify some of this in the proposal for partner_multi_name. See PR https://github.com/OCA/partner-contact/pull/865. I will try to generalize this in a PR for 14. Allowing a flexible number of name parts, and a way to string them together. This should have a global default, that might be overwritten per country (like address format). This should be easily extensible to add more name parts, think about patronymic for Russian, or a nickname (Latin cognomen).
