### ISSUE TITLE
I still can create duplicate. odoo 13

### ISSUE THREAD

**Issue by Alhayah** [OCA/partner-contact#1015]
Hi there,
Thanks for developing this module.
I had installed the module and configure it as below:
Configuration
To configure this module, you need to:
Go to Settings > Users & Companies > Companies.
Select a company.
Choose an option on section Partners.  ( I select "All partners" )

Then I open contacts, chose one contact card > duplicate > save 

1- The duplicate contacts saved with the same phone number and other details. is there a bug or lack of configuration? 

2- Could you tell me how can I configure the ref field, please? 
I would like to use "Passport No" or "Identification No" to be a reference to prevent duplication.  "those fields are made by studio" 

3- Can I configure this module to work on employees? prevernt create an employee with the same "Passport No" or "Identification No. ( those fields are made by odoo ) 

4- Can I contribute with the translation and end-user testing? 

Looking forward your response, 
Thanks in advance,,,

**Comment by Alhayah** [comment]
Dears, @pedrobaeza @NL66278 @MiquelRForgeFlow 
I appreciate your busy schedules, hope you find a moment to have a look at the issue above.
Thanks in advance.

**Comment by Alhayah** [comment]
Hello,
Can anyone help me out? 
@rvalyi @ovnicraft @cmayo

**Comment by NL66278** [comment]
@Alhayah Please start by telling about what module you are talking.

As for employee's. The partner modules are not dependend generally on hr modules. So no, they will not out of the box work for employee's.

**Comment by dnplkndll** [comment]
just looking over this project code, the only prevent save option is partner_ref_unique and uses just ref. The dedups are post create process. 
you could and an onchange to that field like:
What we were trying to do next was make the UI element be a clickable link or redirect to dup on acknowledgment. 
```
    @api.onchange('passport_id')
    def _onchange_passport_id(self):
        if self.passport_id:
            existing_passport_id = self.search([('passport_id','=',self.passport_id.strip())])
            if existing_passport_id:
                partner_vals = []
                message = 'This Passport No is already used in the following records:'
                for partner in existing_street:
                    base_url = self.env['ir.config_parameter'].sudo().get_param('web.base.url')
                    action = self.env.ref('contacts.action_contacts').id
                    url = '{0}/web#id={1}&action={2}&model=hr.employee&view_type=form&cids=1'.format(base_url,partner.id,action)
                    partner_vals.append('{0}, {1}, {2}\n'.format(partner.id,partner.name,url))
                    warning_message = {
                       'title': _('Record already Exist!'),
                       'message': _('{0}\n {1}'.format(message, '\n'.join(partner_vals)))
                    }
                return {'warning': warning_message}

**Comment by moaadbourhim** [comment]
did you find any solution?
