### ISSUE TITLE
[13.0] [BUG] base_location_geonames_import bug with import

### ISSUE THREAD

**Issue by vanderperre** [OCA/partner-contact#1025]
After installed module :
define in system parameter the new accessible address : http://download.geonames.org/export/dump/%s.zip
(see doc of the module of how to make it).
go to contact >>> configuration >>> import from geoname
fill it with belgium
then : error : duplicate key value violates unique constraint "res_country_state_name_code_uniq"

odoo.addons.base_location_geonames_import.wizard.geonames_import: Starting to download http://download.geonames.org/export/dump/BE.zip
odoo.addons.base_location_geonames_import.wizard.geonames_import: The geonames zipfile has been decompressed
odoo.addons.base_location_geonames_import.wizard.geonames_import: Starting to create the cities and/or city zip entries
odoo.sql_db: bad query: INSERT INTO "res_country_state" ("id", "create_uid", "create_date", "write_uid", "write_date", "code", "country_id", "name") VALUES (nextval('res_country_state_id_seq'), 2, (now() at time zone 'UTC'), 2, (now() at time zone 'UTC'), '51.41667', 20, 'Marksken') RETURNING id
ERROR: duplicate key value violates unique constraint "res_country_state_name_code_uniq"
DETAIL:  Key (country_id, code)=(20, 51.41667) already exists.

![Screenshot 2020-11-27 at 10 41 19](https://user-images.githubusercontent.com/55125626/100435501-4d9c7f80-309e-11eb-8a6f-0f73b24e6641.png)

**Comment by pedrobaeza** [comment]
That address doesn't serve, as the format is totally different. Regular downloads are up again.

**Comment by skanndar** [comment]
Hi @pedrobaeza, I have the same issue when trying to import the russian db. 
It also happens with some other ones...

![image](https://github.com/OCA/partner-contact/assets/15900339/ee9fdb52-459c-4e86-a5c2-f8c99fabaa93)


![image](https://github.com/OCA/partner-contact/assets/15900339/e38a35df-6031-4daf-9ff9-d6e3d3c4e344)

Could I modify the constrain adding 'id' to unique block?:    

original:
_sql_constraints = [('name_code_uniq', 'unique(country_id, code)', 'The code of the state must be unique by country !')]

modified: 
_sql_constraints = [('name_code_uniq', 'unique(**id**, country_id, code)', 'The code of the state must be unique by country !')]

**Comment by pedrobaeza** [comment]
That's actually making the constraint useless. Check why there's already such state and the system is not finding it. It's probably a bad state code or name.

**Comment by skanndar** [comment]
@pedrobaeza thank you for the quick response. gracias.
I've checked the RU zip file and it is quite difficult to understand. (cyrilik)
My guess is that there are many codes missing / blank.

Is there a way that I can import the rest of records that are not duplicated? instead of breaking the constrain...


> That's actually making the constraint useless. Check why there's already such state and the system is not finding it. It's probably a bad state code or name.

**Comment by pedrobaeza** [comment]
Maybe the problem is that you need to map another column for getting the code, like we do in https://github.com/OCA/partner-contact/blob/13.0/base_location_geonames_import/data/res_country_data.xml

**Comment by skanndar** [comment]
@pedrobaeza 
I have a look, thank you.

But still I have the question. Is there a way for the code to continue running after the error from the constrain is raised?

**Comment by pedrobaeza** [comment]
Not without touching the code and handling such duplication.

**Comment by skanndar** [comment]
@pedrobaeza 
I have found the problem, at least one code is repeated in the RU csv file, line 3879...


| Código de país | Código postal | Nombre de la localidad | Nombre de la región        | Código de estado | Nombre de la subregión | Vacío | Latitud   | Longitud | Nivel de precisión |
|----------------|---------------|-----------------------|----------------------------|------------------|-----------------------|-------|-----------|----------|--------------------|
84.3797  | 4                  |
| RU             | 453885        | Узя                   | República de Bashkortostán | 08               | Distrito de Meleuzov   |       | 53.2245   | 53.6348  | 1                  |
| RU             | 468320        | Байконур              | Baikonur                  | 08               |                       |       | 52.4044   | 54.6062  | 1                  |

If I modify the csv (change the code or delete the records), how can I upload it to Odoo using the import tool? Or is there some other way?

**Comment by pedrobaeza** [comment]
There's no mechanism right now for importing manually a file. You should hack the module to do it.

Report the error to Geonames for them to fix the code problem.
