### ISSUE TITLE
[14.0] base location, partner view very slow

### ISSUE THREAD

**Issue by fmdl** [OCA/partner-contact#1073]
Hi

Create database, import French zip (60 000).
Create a new partner.
If the field city_id is empty, and allowed_zip_ids is a really big because domain = [].
--> the view is very slow

@pedrobaeza

**Comment by pedrobaeza** [comment]
Indeed I have seen the problem, but there's a solution without losing the feature (and doing it even more powerful), and I have pushed it directly to the branch, as this can be considered a serious bug. Closing then this issue. Thanks for reporting.
