### ISSUE TITLE
[14.0] partner_firstname, Import Invoice Address without name fails

### ISSUE THREAD

**Issue by CRogos** [OCA/partner-contact#1088]
When trying to import Invoice Addresses from excel with an empty value in the "Name" or "Last name" column, I get the following error message.

`Unknown error during import: <class 'AttributeError'>: can't set attribute at 10 different rows: `

No more details in UI and logs. 

Adding a column with non-empty test data for "name", or uninstalling the partner_firstname module the import is working.

**Comment by neckhair** [comment]
I also think that requirement for a name on contacts of type "invoice" should be lifted. It leads to a lot of confusing records, because you need to repeat the company name if you don't have an explicit name of the invoice address.

**Comment by neckhair** [comment]
For the future reader: Setting `is_company = False` solves the problem. And I think it's even kind of correct, since it's neither a company nor a person, but an invoice address...
