### ISSUE TITLE
base_contact improvement: add ISO codes

### ISSUE THREAD

**Issue by alejandrosantana** [OCA/partner-contact#109]
Currently _res.country_ already contains "ISO 3166-1 alpha-2" country code. (see http://en.wikipedia.org/wiki/ISO_3166-1)

It may be interesting to:
- add also "alpha-3" and "numeric" codes to countries.
- add support for states/provinces ISO codes (http://en.wikipedia.org/wiki/ISO_3166-2).

We are willing to contribute with it to OCA, but two questions arise:
- Is it interesting enough for OCA? (I believe so, as it spans every country)
- Where to make the enhancements: in base_location or new module(s)?

**Comment by pedrobaeza** [comment]
> - add also "alpha-3" and "numeric" codes to countries.

This doesn't mean very interesting, because it is not used in any place.

> - add support for states/provinces ISO codes (http://en.wikipedia.org/wiki/ISO_3166-2).

This kind of standarization is also not very used widely. Instead, NUTS is used more. Check the PR for that of our partner Antonio: https://github.com/OCA/partner-contact/pull/107

**Comment by alejandrosantana** [comment]
OK, fair enough. We just needed something related with that and wished to know if it was useful for anyone else.
But I see more use of NUTS, as you say.
