### ISSUE TITLE
[8.0] Fix install of partner_firstname

### ISSUE THREAD

**Issue by bwrsandman** [OCA/partner-contact#11]
In the 8.0 branch, the following error occurs when installing partner_first name

```
ERROR openerp_test openerp.sql_db: bad query: ALTER TABLE "res_partner" ALTER COLUMN "lastname" SET NOT NULL

Traceback (most recent call last):
File "openerp/sql_db.py", line 230, in execute
res = self._obj.execute(query, params)
IntegrityError: column "lastname" contains null values
```

This could probably be fixed by defaulting lastname to something, or revisiting which fields should be required.

**Comment by eLBati** [comment]
Just installed and used partner_firstname on v8 on a fresh DB without problems. So https://github.com/OCA/partner-contact/pull/14
Let's see what travis says

**Comment by bwrsandman** [comment]
There are also the tests.
