### ISSUE TITLE
[partner_affiliate] VAT and address are hidden for the Affiliate companies

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/partner-contact#1134]
The module 'partner_affiliate' allows to separate between contacts in a company, and affiliate companies. That's good.
However once you assign a parent company to an affiliate, some of the fields in the affiliate, like the address, VAT, become read-only. See for example https://github.com/odoo/odoo/blob/14.0/odoo/addons/base/views/res_partner_views.xml#L202

Obviously this is not what we would expect, as an affiliate, being an business entity, will in most of the cases have a distinct address and possibly VAT.

Alternatively one could use module 'partner_group' https://github.com/OCA/partner-contact/tree/12.0/partner_group but this module, as not using the 'parent_id' will not provide the aggregation capabilities provided by partner_affiliate.

So, in my opinion we must remove changes such as https://github.com/odoo/odoo/blob/14.0/odoo/addons/base/views/res_partner_views.xml#L202 to limit them only when the partner is not a company.

@StephanRozendaal @alexandreduf what would be your opinion?

**Comment by JordiBForgeFlow** [comment]
@sergio-teruel you were involved in the 'partner_group' module. Perhaps you have an opinion on this matter.

**Comment by NL66278** [comment]
Maybe in some cases partner_multi_relation can be an alternative?

**Comment by JordiBForgeFlow** [comment]
@NL66278 having the parent_id introduces the possibility to aggregate numbers up the hierarchy, which is very interesting. To me what I described looks like a limitation of the partner_affiliate

**Comment by sergio-teruel** [comment]
@JordiBForgeFlow We are using partner_company_group more than partner_group,

**Comment by JordiBForgeFlow** [comment]
Proposed PR in https://github.com/OCA/partner-contact/pull/1136
