### ISSUE TITLE
[partner_firstname] can't rename partner if company in v7

### ISSUE THREAD

**Issue by riess82** [OCA/partner-contact#114]
Using Partner_firstname.
I could not rename partners if they are a company.

I had to change the return of function _write_name from:
return self.write(cursor, uid, partner_id, vals, context=context)
to:
return self.write(cursor, uid, [partner_id], vals, context=context)

**Comment by pedrobaeza** [comment]
With which module?

**Comment by riess82** [comment]
partner_firstname, I updated the first post for easier reading.

**Comment by pedrobaeza** [comment]
If you have found a solution, please propose a PR against the branch

**Comment by ehdem** [comment]
@riess82 : I try to reproduce your issue, but I can't.
- First test: I created a partner with firstname and lastname, I updated the fields and It works fine.
- Second test: I created a company and I updated; It woks fine. Just one, a company hasn't firstname.

Can you explain how to reproduce this issue ?

**Comment by bwrsandman** [comment]
@riess82 I can't reproduce this issue either, maybe it's something to do with the other modules you have installed.

Have you tried with only partner_firstname installed? What other modules do you have installed?

**Comment by riess82** [comment]
Sorry for my late reply. It might come from some other module, I'm assigned to something completely different atm so I can't test. I'll Close this thread as it seems to be my problem and not that of the module.
