### ISSUE TITLE
Deprecate base_contact and split it in other modules

### ISSUE THREAD

**Issue by yajo** [OCA/partner-contact#119]
After discussion in https://github.com/OCA/partner-contact/pull/118, it became clear that the current implementation of _base_contact_ is not what its name suggests (a base for contact modules), but a collection of unrelated functionalities that remain from old times and block further development.

So, my suggestion is:
1. Create a new base module for contact stuff. It will just have a sheet called _Personal data_ that will display only for contact partners. It's intended to serve as a base for other modules, so it will do nothing more. Let's call it _contact_base_.
2. Split the functionalities from _base_contact_ in 3 modules:
   1. _contact_in_several_partners_: set several job positions in different companies per contact.
   2. _contact_birthdate_.
   3. _contact_nationality_.
3. Deprecate _base_contact_, making it a dummy module that depends on those 3 new modules. This way, after next update all will continue working as it did before.
4. Remove _base_contact_ whenever branch 9.0 appears.

After all that is done, new modules for contact personal data may come easier. I myself will submit some: contact gender, disability, and some others just for the l10n-spain team.

My company needs all these changes, so I'll start working on this right now unless somebody tells me they are already doing it or have a better roadmap for those modules. I don't mind having our own fork forever if nobody wants these changes, but I think this work will benefit everyone, so I'd prefer to have approval from the community and give back a little of the help we have received and appreciate so much.

**Comment by pedrobaeza** [comment]
I agree, but prefer to prepend partner_ to all modules

**Comment by yajo** [comment]
No problem. Do you mean for instance _partner_contact_birthdate_ or _partner_birthdate_?

**Comment by pedrobaeza** [comment]
It seems to be more coherent to name them partner_contact_base, partner_contact_birthdate...

**Comment by yajo** [comment]
:+1:

**Comment by yvaucher** [comment]
IMO a contact being a partner I don't see the need of adding `partner_` to all module technical names

And indeed a split of functionalities would be better.

**Comment by yajo** [comment]
Then please come to a consensus. For now I've started with @pedrobaeza suggestion. You can track progress if you want in https://github.com/grupoesoc/partner-contact/tree/deprecate-base_contact.

**Comment by pedrobaeza** [comment]
@yvaucher, partner prefix identify the "area" you are working with.

**Comment by yvaucher** [comment]
@pedrobaeza area should be given in `__openerp__.py` as category and partner_contact isn't an area in term of object. Plus renaming modules makes difficulties in migrations and we have no naming convention for module written in https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md

**Comment by pedrobaeza** [comment]
This was also debated in the past, because partner itself is not an area as you say, but it's a very important topic not to be included in the names. Odoo itself was debating to split base module to include all res.partner related stuff in a partner module. I was the one to think on not to put `partner_` also until I speak with @hbrunn about it.

**Comment by yvaucher** [comment]
@pedrobaeza What about a talk with a PR on https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md ?
