### ISSUE TITLE
Port MPs from launchpad to here

### ISSUE THREAD

**Issue by bwrsandman** [OCA/partner-contact#12]
- [x] Move what you have write access to. E.g. I can move savoirfairelinux branches
- [x] Provide links to the lp porting guide for OCA on the MRs which are still open
- [x] Rate resubmit and reject the MRs
- [x] Merge missing commits

**Comment by eLBati** [comment]
Posted a message on every MP

**Comment by bwrsandman** [comment]
Thank you @eLBati!

**Comment by guewen** [comment]
I noticed 2 extra revisions on the Launchpad branch that are missing there:
http://bazaar.launchpad.net/~partner-contact-core-editors/partner-contact-management/7.0/revision/41
http://bazaar.launchpad.net/~partner-contact-core-editors/partner-contact-management/7.0/revision/42

The last one here https://github.com/OCA/partner-contact/commits/7.0 corresponds to the rev 40 on launchpad.

**Comment by bwrsandman** [comment]
Can we cherry-pick those two commits?

**Comment by bwrsandman** [comment]
[41](http://bazaar.launchpad.net/~partner-contact-core-editors/partner-contact-management/7.0/revision/41) is in PR at #62
[42](http://bazaar.launchpad.net/~partner-contact-core-editors/partner-contact-management/7.0/revision/42) is already in the code
