### ISSUE TITLE
Add parish level on state

### ISSUE THREAD

**Issue by damendieta** [OCA/partner-contact#1214]
In Ecuador, we need the parish for a client in order to generate some legal reports, so, we need the following structure:

- Country -> State -> Parish.
- 
**Describe the solution you'd like**
Create a new module, maybe base_parish to add the new concept.

**Describe alternatives you've considered**
Use the city field to fill this information, but city is also required.

**Comment by damendieta** [comment]
After talking with other developers, the final idea is to create a module called base_address_parish, that will depend on base_address_city and will add a new model res.parish as a new level below res.city.

The idea will be:
- Add the new model.
- Add a field city_id on the new module as a m2o to res.city.
- Add a new field, parish_id on res.partner, with a domain to select only the ones that belong to the selected city.
- Add the new field in the address of the contact form view.

**Comment by damendieta** [comment]
@pedrobaeza could you please give us one comment about this. We will develop the module, just need some guidence to choose the right path.

**Comment by pedrobaeza** [comment]
Next time, a link like https://en.m.wikipedia.org/wiki/Parishes_of_Ecuador will be helpful for explaining concepts that are not very clear.

So if I understand correctly, you have several cities inside a parish?

**Comment by damendieta** [comment]
Hi, sorry, you are right, I should give more information.

In Ecuador, our [territorial division](https://es.wikipedia.org/wiki/Organizaci%C3%B3n_territorial_de_Ecuador) has the following parts.

- Country (país)
- - State (provincia)
- - - Canton (cantón).
- - - - Parish (Parroquia)

Definition for canton: https://www.collinsdictionary.com/dictionary/english/canton
Definition for parish: https://www.collinsdictionary.com/dictionary/english/parish

This is the information source we are using: [CENSO_2016_TTHH_Listado_prov-cantones-parroquias.pdf](https://www.obraspublicas.gob.ec/wp-content/uploads/downloads/2016/10/CENSO_2016_TTHH_Listado_prov-cantones-parroquias.pdf)

As Odoo has only country and state, we need to put canton and parish informations somewhere else, we want to use res.city as canton, city and canton are not the same but it will work most of the time. But for parish, we need to create another model.

With this module, the user will be allowed to select:

Country -> State -> City (Canton) -> Parish

Thanks a lot.

Daniel.

**Comment by celm1990** [comment]
Any comment are welcome https://github.com/OCA/partner-contact/pull/1223
thanks so much
