### ISSUE TITLE
In the contact view, the search by pricelist in the search field is not available

### ISSUE THREAD

**Issue by LESTRAT21** [OCA/partner-contact#1217]
module: partner_pricelist_search
version: 14.0

Hello.
I've just installed your module, thanks for these relevant features.
But, in the contact view, the search by pricelist in the search field is not available!

![pricelist](https://user-images.githubusercontent.com/65964282/152361002-1f326829-67ff-48d1-a58d-73f5ea8bc525.png)

However the new smart button called “Customers” in pricelist form view is here.

Thanks for your assistance,

**Comment by pedrobaeza** [comment]
It's available in the custom search, not in the quick search. You can also navigate from the pricelist to the customers with such pricelist.
