### ISSUE TITLE
base_location_geonames_import 404 Error

### ISSUE THREAD

**Issue by emagdalenaC2i** [OCA/partner-contact#1253]
## Module
base_location_geonames_import.

## Describe the bug
The zip file are no longer in that path

## To Reproduce
**Affected versions**: I think all versions

1. Go to the menu Contacts > Configuration > Localization > Import from Geonames.
2. In the wizard, select one or several countries and click on the Import button

**Comment by rousseldenis** [comment]
> ## Module
> base_location_geonames_import.
> 
> ## Describe the bug
> The zip file are no longer in that path
> 
> ## To Reproduce
> **Affected versions**: I think all versions
> 
> Steps to reproduce the behavior:
> 
> 1. Go to the menu Contacts > Configuration > Localization > Import from Geonames.
> 2. In the wizard, select one or several countries and click on the Import button

@emagdalenaC2i Sometimes, generated file is void on geoname side. Wait until tomorrow and check if file is correct

**Comment by pedrobaeza** [comment]
This happens eventually when there's a problem in Geonames, but it takes a bit to be recovered. It is a matter of time.
