### ISSUE TITLE
The birthdate_date column contains incorrect values. Error on line xx: unconverted data remains: 1999-04-11

### ISSUE THREAD

**Issue by jmmmmr** [OCA/partner-contact#1256]
## Module
partner_contact_birthdate

## Describe the bug
Pressing the TEST option, when contacts are massively imported and the Date of Birth column is included, this error appears on the line that contains a date of birth:
The birthdate_date column contains incorrect values. Error on line 11: unconverted data remains: 2000-01-01

## To Reproduce
**Affected versions**:
15.0

1. create file to import contacts
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/John/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/John/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link=blue vlink=purple>

display_name | name | birthdate_date
-- | -- | --
1 | 1 |  
2 | 2 |  
3 | 3 |  
4 | 4 |  
5 | 5 |  
6 | 6 |  
7 | 7 |  
8 | 8 |  
9 | 9 |  
10 | 10 |  
11 | 11 | 1/1/2000

</body>

</html>

3. include a date on any line after 10
4. open the option to import contacts
5. upload the file
6. press test
7. error appears

Tip If a correct date is included in any line from 1 to 10, the file is validated correctly and the error does not appear

**Expected behavior**
pressing test should correctly pass the validation of the date, which is in the format dd/mm/yyyy or yy/mm/dddd and later even if only date data is included after line 10, it should load the information to the system.

**Additional context**
AWS
EC
Ubuntu 20
Ubuntu Server 20.04 LTS (HVM), SSD Volume Type - ami-04505e74c0741db8d (64 bits x86) / ami-0b49a4a6e8e22fa16 (64 bits Arm)

**Comment by pedrobaeza** [comment]
This has nothing to do with the module, but with your import dataset or with the import system. Ask on forums about that.
