### ISSUE TITLE
[7.0] Error when displaying res.partner Form view (street field)

### ISSUE THREAD

**Issue by gurneyalex** [OCA/partner-contact#127]
- Go to https://runbot.odoo-community.org/runbot/repo/github-com-oca-partner-contact-134
- Connect to the 7.0 branch 
- Go to Sales -> Customers
- Click on any partner in the kanban view

Expected: nice form view of the partner

Actual: Error message 

![screenshot from 2015-06-10 08 47 11](https://cloud.githubusercontent.com/assets/2032807/8076526/731ecec0-0f4d-11e5-8791-7dcfc4579cae.png)

**Comment by StefanRijnhart** [comment]
Fixed for 8.0 (some time ago) https://github.com/OCA/partner-contact/pull/135

**Comment by NL66278** [comment]
Problem no longer exists on 7.0 either
