### ISSUE TITLE
Key (zip_id)=(1) is not present in table "res_city_zip".

### ISSUE THREAD

**Issue by carlos-birtum** [OCA/partner-contact#1297]
Hello,
When migrating a database version 11 to 15 I get the following error from the base_location module:

module base_location: creating or updating database tables 
2022-06-29 23:12:40,079 48289 ERROR waynabox_16 odoo.sql_db: bad query: ALTER TABLE "res_partner" ADD FOREIGN KEY ("zip_id") REFERENCES "res_city_zip"("id") ON DELETE set null
ERROR: insert or update on table "res_partner" violates foreign key constraint "res_partner_zip_id_fkey"
DETAIL:  Key (zip_id)=(1) is not present in table "res_city_zip".

Thanks in advance for reviewing it

**Comment by pedrobaeza** [comment]
Your database seems corrupt or you haven't executed the migration scripts between both versions. In any case, I'm afraid this is out of the scope of this issue tracker, so closing.

**Comment by carlos-birtum** [comment]
Thank you very much
