### ISSUE TITLE
[6.1] base_partner_surname and partner_address_ldap are conflicting

### ISSUE THREAD

**Issue by bwrsandman** [OCA/partner-contact#13]
https://github.com/OCA/partner-contact/pull/7#issuecomment-49512838

Both want to add last name to 'res.partner.address'.

I think that field should be added in `base_partner_surname` and if `partner_address_ldap` wants to use it, make it depend on `base_partner_surname`

**Comment by NL66278** [comment]
res.partner.address has been replaced by integrated res.partner. And the issue of modules adding the same field has been resolved by 8.0 by merging field attributes. As version 6.1 is long out of support I will close this issue.
