### ISSUE TITLE
Incompatibility between base_partner_sequence and partner_ref_unique

### ISSUE THREAD

**Issue by Highcooley** [OCA/partner-contact#1309]
## Module
base_partner_sequence
partner_ref_unique

## Describe the bug
base_partner_sequence makes partner_ref read-only, so far so good.
But base_partner_sequence for some reason also introduces a new rule that contacts of a company inherit the partner_ref from the company.
At the same time, partner_ref_unique can either check the uniqueness of a partner_ref over all contacts (default) but then struggles with the base_partner_sequence rule or it only checks on companies but allows for contacts to be non unique.

## To Reproduce
**Affected versions**:
14, 15

1. install bot modules
2. create a company
3. create a contact and try to assign it to a company, or create a contact from a company -> error raises that the reference is not unique

**Expected behavior**
Either the inheriting function of base_partner_sequence should be optional and configurable or base_partner_sequence should check if the other module is installed and if yes not check partners which are assigned to companies.

**Additional context**
If solving this issue is not an option, at least a warning on the partner_ref_unique module is needed that it conflicts with base_partner_sequence and only works in "check companies only" mode.

**Comment by i-vyshnevska** [comment]
the solution https://github.com/OCA/partner-contact/pull/1323
