### ISSUE TITLE
partner_company_group - pre-init hook for performance might be nice

### ISSUE THREAD

**Issue by gdgellatly** [OCA/partner-contact#1325]
https://github.com/OCA/partner-contact/blob/ba5a90bcdade626e14665c594e4ab77d426c91fa/partner_company_group/models/account_move.py#L11

https://github.com/OCA/partner-contact/blob/ba5a90bcdade626e14665c594e4ab77d426c91fa/partner_company_group/models/crm_lead.py#L11

https://github.com/OCA/partner-contact/blob/ba5a90bcdade626e14665c594e4ab77d426c91fa/partner_company_group/models/sale_order.py#L11

Just a standard - If column doesn't exist - create column - default False. It's not terrible or urgent, roughly 8 minute installation time. Mainly a reminder to myself, or maybe a good first issue for someone.

**Comment by pedrobaeza** [comment]
Done in #1324
