### ISSUE TITLE
Coveralls PR check bot broken

### ISSUE THREAD

**Issue by yajo** [OCA/partner-contact#136]
As stated in https://github.com/OCA/partner-contact/pull/104#issuecomment-117522275, the Coveralls check for PR seems to be broken. Currently only 1 LOC is not tested in that PR, and see what [the bot says](https://coveralls.io/builds/2957735):

![captura de pantalla de 2015-07-02 11-00-19](https://cloud.githubusercontent.com/assets/973709/8473504/68bc78ce-20aa-11e5-9d57-31cf70b04fd4.png)

It seems bot's bug.

**Comment by bwrsandman** [comment]
Strange. I did notice something like that. Could you open this issue on https://github.com/OCA/maintainer-quality-tools
