### ISSUE TITLE
partner_address_street3 dependency

### ISSUE THREAD

**Issue by Lionel-cl** [OCA/partner-contact#1484]
Module: partner_address_street3  - odoo v15

I don't understand why this dependency is needed :
`"depends": ["base_view_inheritance_extension"],`

 I read the code and do not see its interest. Especially since it requires the installation of astor more truly maintained.

Did I miss something?

Thank you for your analysis

**Comment by mide-dynapps** [comment]
Hi,
Same issue.
It seems to be obsolete since the migration into v15, the code in the view has been deleted:
https://github.com/OCA/partner-contact/commit/b4a2506f9ef5f7e8da927e601358b185df3ee5a3

It possible to reverse depends to base module only ?

**Comment by janeped** [comment]
Same issue. Possible to remove this dependency?

**Comment by youbo28** [comment]
Had the same problem in ODOO16 solved by download server-tools from OCA  in the repository  bellow 
https://github.com/OCA/server-tools
hope this helps
