### ISSUE TITLE
[16.0] partner_firstname: contact form view double fields

### ISSUE THREAD

**Issue by Bart-dh** [OCA/partner-contact#1490]
https://github.com/OCA/partner-contact/blob/165a8aa3d3b50f4d9231b7925e633e58633b758a/partner_firstname/views/res_partner.xml#L52

Class oe_edit_only seems to be doing nothing as in 16.0 'edit' mode is permanent, resulting in a not so nice form view. Name field is shown twice next to eachother

**Comment by ajjayymahato** [comment]
@Bart-dh Hi there! I would like to work on this issue. Is this issue still open? Can you please assign this issue to me!

**Comment by Bart-dh** [comment]
> @Bart-dh Hi there! I would like to work on this issue. Is this issue still open? Can you please assign this issue to me!

I'm not sure, it was long ago. You could check :)
