### ISSUE TITLE
Errors on Upload/Install v16. Community

### ISSUE THREAD

**Issue by Cujo13** [OCA/partner-contact#1574]
module: partner_multi_relation
version: 16.0

New to Odoo, so I may not be installing this correctly....

**Steps to reproduce**
- ...Studio > Customizations > Import

**Current behavior**
Error message & failure to install: 

Error while importing module 'partner_multi_relation'.

 Module loading partner_multi_relation failed: file /tmp/tmp_xmub_mr/partner_multi_relation/security/ir.model.access.csv could not be processed:
 No matching record found for external id 'model_res_partner_relation' in field 'Model'
No matching record found for external id 'model_res_partner_relation_all' in field 'Model'
No matching record found for external id 'model_res_partner_relation_type' in field 'Model'
No matching record found for external id 'model_res_partner_relation_type_selection' in field 'Model'
No matching record found for external id 'model_res_partner_relation' in field 'Model'
No matching record found for external id 'model_res_partner_relation_all' in field 'Model'
No matching record found for external id 'model_res_partner_relation_type' in field 'Model'
Missing required value for the field 'Model' (model_id)
Missing required value for the field 'Model' (model_id)
Missing required value for the field 'Model' (model_id)
Missing required value for the field 'Model' (model_id)
Missing required value for the field 'Model' (model_id)
Missing required value for the field 'Model' (model_id)
Missing required value for the field 'Model' (model_id) 
 Make sure those modules are installed and try again.
**Expected behavior**

**Comment by NL66278** [comment]
I never tried to install a module through Studio. The proper way would be through the apps menu.
