### ISSUE TITLE
[16.0] base_location: res.city.zip search

### ISSUE THREAD

**Issue by odooNextev** [OCA/partner-contact#1578]
## Module
base_location

## Describe the bug
Searching in `res.city.zip` field without use `search more` can be difficult in Odoo 16.0 because it doesn't allow you to filter based on more than one parameter at a time.
In older versions (for example 12.0), it was possible to search exactly the string you see in the dropdown (space and dot included) and get the results starts with characters in the input.

## To Reproduce
**Affected versions**:

- [ ] 16.0 https://github.com/OCA/partner-contact/pull/1581

1. Create or edit a contact
2. Search a city in `res.city.zip` field (with "Location completion" placeholder) by "zip code, city name"
![image](https://github.com/OCA/partner-contact/assets/93990941/751ab821-1b81-4389-b718-e416a9efa282)

3. You won't get results
![image](https://github.com/OCA/partner-contact/assets/93990941/8632f2de-3c23-49f8-b074-389de18b980c)

**Expected behavior**
Exactly as it was in 12.0 version.
![image](https://github.com/OCA/partner-contact/assets/93990941/e138a08f-a42e-4f8b-87fa-3b27ed9f8079)

**Comment by pedrobaeza** [comment]
It should be a consequence of the several refactorings in the framework and the module.

Pull requests are accepted improving this.
