### ISSUE TITLE
Bad compare onchange_type_selection_id

### ISSUE THREAD

**Issue by ghost** [OCA/partner-contact#160]
On line 169 of res_partner_relation_all.py
is_company = self.type_selection_id.partner_category_other == 'c'

It gives apples/oranges python error...

Not sure what this is supposed to do, it is getting a category but the 'c', 'p' portions of this module are for the is_company flag.  I commented and removed the filter and it now works, but it would be nice of setting the relationship type filtered the right partner dropdown.

**Comment by rafaelbn** [comment]
@idncom you must open issue with the bugtracker template:

> module: l10n_es_pos_simplified_invoice
> version: 8.0
> 
> **Steps to reproduce**
> - ...
> 
> **Current behavior**
> 
> **Expected behavior**

Also take care on tittle

**Comment by ghost** [comment]
Thank you, I actually forked, corrected and submitted a pull request.  We
just submitted our agreement so we can contribute as we find issues.

On Wed, Aug 19, 2015 at 3:44 AM, Rafael Blasco notifications@github.com
wrote:

> @idncom https://github.com/idncom you must open issue with the
> bugtracker template:
> 
> module: l10n_es_pos_simplified_invoice
> version: 8.0
> 
> _Steps to reproduce_
> - ...
> 
> _Current behavior_
> 
> _Expected behavior_
> 
> Also take care on tittle
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/OCA/partner-contact/issues/160#issuecomment-132495411
> .

## 

Best Regards,
Mark Meadows
www.apptuate.com
636.678.9924
