### ISSUE TITLE
[16.0] base_location_geonames_import: Can't import postal codes from Portugal

### ISSUE THREAD

**Issue by oo-landoo** [OCA/partner-contact#1634]
![portugal](https://github.com/OCA/partner-contact/assets/146071362/70f2d664-e51e-4db2-8e3c-5f279b2795fc)

This is the wizard of the configuration to insert postal codes in odoo.

![portugal_2](https://github.com/OCA/partner-contact/assets/146071362/0b47fcaf-8b16-4f85-8114-df3014235424)

The problem is that when I click on the import button, the screen gets frozen and and it stays charging all the time.

Can someone help me with this issue?

Thanks

**Comment by pedrobaeza** [comment]
The load is slow, so that can be normal. Let it some time. If never stops, try to reproduce the problem in runboat. If not reproducible, then it's something on your deployment.

**Comment by oo-landoo** [comment]
Hi,

I tried again in my deployment and it didn't work again. Because of that, I tried to reproduce the problem in runboat and it has worked with other countries except with Portugal. The error that appeared on the screen was related with connection issues.

Can you help me with this?

Thanks

**Comment by pedrobaeza** [comment]
Put exact error here.

**Comment by oo-landoo** [comment]
Hi,

Here is the link of the video to show the exact error.

https://drive.google.com/file/d/1nKRUtqqxayRfzPIZDnDrynJcDjJOIEn3/view?usp=drive_link

In the video, we can see that the importation is correct in runboat with Austria. However, when we want to import Portugal there is a connection error.

Thanks

**Comment by pedrobaeza** [comment]
There's no access to the video.

**Comment by oo-landoo** [comment]
Try it now.

**Comment by pedrobaeza** [comment]
The problem depicted in runboat is because runboat has very few limits for avoiding long processes bottlenecks, and it seems Portugal has a lot of cities or any thing that gets in an infinite loop. Trying in local, it indeed never ends, so the problem is real, but right now no clue about what's going on, so I let this open to see if someone has any hint about this.

**Comment by oo-landoo** [comment]
Thank you, Pedro.
