### ISSUE TITLE
partner_contact_address_default  odoo16

### ISSUE THREAD

**Issue by vtomasi** [OCA/partner-contact#1659]
the module works but in the drop-down menu where you can choose the shipping address it is limited to 99 lines. If a company has more than 99 locations, those beyond 99 are not exposed

Vittorio

**Comment by gdgellatly** [comment]
Well I think this is a rare case, in those cases, I would add a custom view to use `widget="many2one"` although to be honest, I am not sure why the selection widget is used when the same outcome can be acheived with an m2o widget with no create, edit, open options set.

**Comment by pedrobaeza** [comment]
Yes, any PR changing that is welcome.
