### ISSUE TITLE
 Standalone Contact address not inherited from the original contact

### ISSUE THREAD

**Issue by mhapponen** [OCA/partner-contact#166]
Tested modules partner_contact_in_several_companies and res_partner_affiliate and wonder whether following is designed feature or a bug: 
I have two companies, company A being the 'mother company' and company B and C the daughters or affiliates. Company A is having centralized invoicing department (Contact of type invoice address in company A data) which is used by B and C. I maintain a special invoicing address for the A invoicing department, which is different to the company A regular visiting address. I'd like to use the A invoicing dept. address as the invoice address when company B and C are creating sales orders and invoices. However, when I create invoice for B and C I get company A company visiting address to the invoice, not the A's invoicing department address as I would expect. 

Further, if you would change the invoicing dept. address at some point I would like to change only one address and after that being able to invoice for company B and C with the updated invoicing address data and avoid to update also addresses behind B and C customers.

**Comment by NL66278** [comment]
If this problem occurs on supported versions of Odoo, please re-open issue.
