### ISSUE TITLE
base_location_geonames_import unicodecsv error

### ISSUE THREAD

**Issue by angelocala94** [OCA/partner-contact#167]
Hi,
i have installed unicodecsv with "pip install unicodecsv".
While trying to import Italian provinces, the wizard show me this error:

for row in unicodecsv.reader(
AttributeError: 'NoneType' object has no attribute 'reader'
Detailed screenshot: https://www.dropbox.com/s/5je1mb9qawtia8i/Screenshot%202015-09-03%2016.25.32.png?dl=0

Thanks

**Comment by pedrobaeza** [comment]
You installed the module in an environment where you had unicodecsv, and now the environment where you are running Odoo doesn't, so it's a problem of your installation.

**Comment by angelocala94** [comment]
Hi Pedro, is a new installation, i've installed odoo using an install script found on github, and i've installed the modules by copying their files in the addons folder. Can you help me to solve this?

**Comment by pedrobaeza** [comment]
Sorry, but the problem is that. Library is not detected and the code goes to https://github.com/OCA/partner-contact/blob/8.0/base_location_geonames_import/wizard/geonames_import.py#L37.

I can't help you because it's a matter of your installation, not the code.

**Comment by conerix** [comment]
Got the same problem.. with fresh installation used the following installation script
https://github.com/conerix/odoo-install-scripts/blob/master/ubuntu-14-04/odoo_install.sh
and after installation was done i did a 
pip install unicodecsv

**Comment by qupro** [comment]
I got the same problem (Odoo 9.0c , ubuntu 14.04), and I had installed unicodecsv with
`sudo apt-get install python-unicodecsv`.

After the error I did a `sudo pip install unicodecsv --upgrade` getting this:

> Downloading/unpacking unicodecsv from https://pypi.python.org/packages/6f/a4/691ab63b17505a26096608cc309960b5a6bdf39e4ba1a793d5f9b1a53270/unicodecsv-0.14.1.tar.gz#md5=c18ffe8ded29a4f429224877b2b34252
>   Downloading unicodecsv-0.14.1.tar.gz
>   Running setup.py (path:/tmp/pip_build_root/unicodecsv/setup.py) egg_info for package unicodecsv
> 
> Installing collected packages: unicodecsv
>   Found existing installation: unicodecsv 0.9.4
>     Not uninstalling unicodecsv at /usr/lib/python2.7/dist-packages, owned by OS
>   Running setup.py install for unicodecsv
> 
> Successfully installed unicodecsv
> Cleaning up...

Then I restart the server with `sudo service odoo-server restart` and now it works.

Note: I don't get this error in a Debian 8.3 installation
