### ISSUE TITLE
base_location_geonames_import: Where is the wizard

### ISSUE THREAD

**Issue by ybofr** [OCA/partner-contact#168]
Hi I installed the module on Github, but I see no wizard.

Thanks for help

Eva P.

**Comment by eLBati** [comment]
Hi,
sales, configuration, address book, localization, import from geonames

**Comment by pedrobaeza** [comment]
I have created a PR to improve the README: https://github.com/OCA/partner-contact/pull/169. Please review it.

**Comment by ybofr** [comment]
Hi,

The problem is that the runbot of the community for partner-contact does not have sales installed in standard.

Regards

**Comment by pedrobaeza** [comment]
That's not true. What you don't have is defined in admin user is Sales Manager permission. That's why I included that on my README improvement.

**Comment by ybofr** [comment]
Just tested the PR 169 without success. 
1. Installed the sales module
2. I checked that the import module is active.
3. I assigned the Sales Manager permission to the administrator
<img width="336" alt="local_modules_-_odoo" src="https://cloud.githubusercontent.com/assets/7601880/9682138/c606a92c-52fb-11e5-9fee-e3f8ee8db857.png">

but still no " localization, import from geonames"
<img width="858" alt="users_-_odoo" src="https://cloud.githubusercontent.com/assets/7601880/9682088/52147bfc-52fb-11e5-8932-0cf517bfbf10.png">
<img width="647" alt="menubar" src="https://cloud.githubusercontent.com/assets/7601880/9682099/7220a2b8-52fb-11e5-981d-c88ea6862e86.png">

**Comment by pedrobaeza** [comment]
Sorry, we should tell you that you need to activate technical feature also, but as is always needed... :wink: I've improved again the README.
