### ISSUE TITLE
[base_partner_merge] merging two partners both followed by the same partner fails.

### ISSUE THREAD

**Issue by charbeljc** [OCA/partner-contact#179]
To reproduce with demo data, make two copies of Agrolait. Both will be followed by your user's partner.
Attempt to merge them raises a constraint error saying: "Error, a partner cannot follow twice the same object."

**Comment by rafaelbn** [comment]
@charbeljc we can close this issue as it has been solved here https://github.com/OCA/partner-contact/pull/182 by your self. It's not necessary to open issue and pr.

**Comment by rafaelbn** [comment]
Please check https://github.com/OCA/partner-contact/issues/196
