### ISSUE TITLE
Create and Edit issue on res.partner

### ISSUE THREAD

**Issue by louisvbst** [OCA/partner-contact#1802]
https://github.com/OCA/partner-contact/blob/b90146e21c19f6a6b004da3b101dbb7d98e24e60/partner_firstname/models/res_partner.py#L114

Hi,

This causes a problem because 'name' might already be en fields_list. Thus, it might be duplicated in the list of fields_list. This causes a stacktrace when we try to create a res.partner from the form view of a related record (a sale.order for example) and we click on 'create and edit'. There should be a check that 'name' is not already in fields_list

Best regards

**Comment by pedrobaeza** [comment]
Fixed in #1794
