### ISSUE TITLE
[16] partner_contact_access_link Incorrect redirection when creating a child contact without saving (Odoo 16) Bug

### ISSUE THREAD

**Issue by fcvalgar** [OCA/partner-contact#1878]
Version: Odoo 16.0

Steps to reproduce:

1. Go to the Contacts menu.
2. Create a new child contact from a parent contact's form.
3. Use the provided link to access the child contact without saving first.
4. Current behavior: Instead of redirecting to the created child contact, it opens a form to create a new contact. This doesn't happen if the child contact is saved first.

Expected behavior: The link should correctly redirect to the newly created child contact, even if it hasn't been saved.

Video/Screenshot:
https://www.loom.com/share/e093ff6473844678872ab52ed0fe4520?sid=7464ee78-e342-47b4-af60-49a3e206fed9

@moduon MT-7663 MT-7665

**Comment by rafaelbn** [comment]
Solution in https://github.com/OCA/partner-contact/pull/1887
