### ISSUE TITLE
[8.0] partner_academic_title - add academic tittle to Company but comanies cannot have academic tittle

### ISSUE THREAD

**Issue by rafaelbn** [OCA/partner-contact#217]
module: partner_academic_title
version: 8.0

**Steps to reproduce**
- Go To a Company see field "academic tittle"

**Current behavior**
- You can see "academic titlle" in companies

**Expected behavior**
- "Academic tittle" is only for non-companies (contacts)

![14-12-2015 13-48-48](https://cloud.githubusercontent.com/assets/8736623/11781445/454c440e-a26a-11e5-8bd9-f510260ed32f.png)

**Comment by rafaelbn** [comment]
Could you review this issue @sbidoul @adrienpeiffer please?

**Comment by sbidoul** [comment]
I personally agree it's a bug. @adrienpeiffer will look into it.

**Comment by adrienpeiffer** [comment]
I just propose a correction for this one on #288
