### ISSUE TITLE
[8.0] partner_firstname Error when creating a partner with is_company set to True

### ISSUE THREAD

**Issue by feketemihai** [OCA/partner-contact#221]
module: partner_firstname
version: 8.0

Steps to reproduce

Creating tests in module partner_create_by_vat, i set only name and is_company set to True, at launching tests locally, or without the partner_firstname everything is ok, when i launch the tests with the partner firstname, it raises error about EmptyNames

Current behavior

The create method is inherited in the partner_firstaname module, after computin firstname and lastname (the name of the company if is_comoany set to True), the "name" key and value is deleted from the vals, but after the _inverse_name function is called, so without having the "name" in vals, firstname and lastname are set to False.

Expected behavior

Not to raise error.

**Comment by moylop260** [comment]
@Yajo 
Could you see this issue, please?

**Comment by feketemihai** [comment]
@moylop260 @Yajo The ideea is that the _inverse_name function is only called when installing the module, can you see the log from the partner_create_by_vat PR. If i keep the name in dict there are tests in partner_firstname that are failing.

**Comment by yajo** [comment]
Please see https://github.com/OCA/partner-contact/pull/216#discussion_r48022388 and close this.

**Comment by feketemihai** [comment]
@Yajo Thanks for the review, it is ok now.
