### ISSUE TITLE
[7.0] partner_address_street_3 appears, but empty

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/partner-contact#240]
Hi all,

Module "partner_address_street_3" now appears under this repo, branch 7.0, but empty. I can see that there's a PR https://github.com/OCA/partner-contact/pull/126 that plans to add it. 

Is there a reson for this module to exist, but empty?

**Comment by feketemihai** [comment]
It seems to come from the Transifex Translation:

https://github.com/OCA/partner-contact/commits/7.0/partner_address_street3

see the History Tab. 
The module is only available in the 8.0 branch.
