### ISSUE TITLE
QUESTION: [ADD] partner_search_by_vat: Is here a project valid?

### ISSUE THREAD

**Issue by moylop260** [OCA/partner-contact#241]
We want contritubute follow module: [partner_search_by_vat](https://github.com/Vauxoo/addons-vauxoo/blob/8.0/partner_search_by_vat/model/res_partner.py)
Is here a correct project for this module?

**Comment by moylop260** [comment]
cc @pedrobaeza

**Comment by elicoidal** [comment]
@moylop260 I think this is correct

**Comment by pedrobaeza** [comment]
Yeah, that's it!

**Comment by moylop260** [comment]
I got it
Thank you
