### ISSUE TITLE
[partner_firstname] init script performance issue

### ISSUE THREAD

**Issue by brmasson** [OCA/partner-contact#260]
## partner_firstname: 8.0

The initialization script (`partner_firstname/data/res_partner.yml`) took several hours to process a large amount of partners (in excess of 100k in my case).

I was able to replicate most of the script's functionality using a couple SQL statements which took only a few seconds to run.
It is my belief that the script's performance can be significantly improved without too much work simply by using SQL statements where appropriate.

Here are the SQL queries I used. Note that unlike the script in `res_partner.yml`, these statements will recompute `firstname`, `lastname` for all records, including those where these values are already populated.

``` sql
BEGIN;
-- Trim 'name'
UPDATE res_partner
SET name = trim(both ' ' from regexp_replace(name, '\s+', ' '))
;

-- Compute 'name'
UPDATE res_partner
SET lastname  = trim(both ' ' from substring(trim(both ' ' from name) from '^\S*\s')),
    firstname = trim(both ' ' from substring(trim(both ' ' from name) from '\s.*$'))
;
COMMIT;
```

**Comment by dcorio** [comment]
I'm installing this module on V11 and facing the same problem with ~ 135K partners.

**Comment by pedrobaeza** [comment]
Please propose a PR with that changes.

**Comment by eLBati** [comment]
Just as per https://github.com/OCA/partner-contact/issues/674 :grin: 

cc @taifu

**Comment by taifu** [comment]
Mine query #674 was a little bit more similar to the code. But nevertheless better this than nothing
