### ISSUE TITLE
base_partner_merge v7 destroys database when it is uninstalled

### ISSUE THREAD

**Issue by jalzaga** [OCA/partner-contact#263]
Affects v7

When base_partner_merge is uninstalled it drops the partner.id column from the database. Consequently, all the foreign keys are lost and the database is inaccessible. You need to restore the whole environment.
The problem is that the module inherits the class res_partner and adds the column “id”. When the module is uninstalled it drops the column “id” from the res_partner model and also from the database

**Comment by hbrunn** [comment]
yes, uninstalling stuff in <8.0 is a problem. For your version, I can't think of a better suggestion than: Don't uninstall stuff
