### ISSUE TITLE
UI for base_location_nuts needs improvement?

### ISSUE THREAD

**Issue by dreispt** [OCA/partner-contact#267]
IIMO the placement of the NUTS fields in the Partner form looks clumsy.
Would it be a problem to move them into a NUTS notebook page?

![2016-04-21 12_53_37-contacts - odoo - firefox developer edition private browsing](https://cloud.githubusercontent.com/assets/1246629/14708071/58bbc4a4-07c0-11e6-882a-4dad8f176063.png)

**Comment by pedrobaeza** [comment]
I see the place the right one because it goes with the rest of the address. Maybe, what it can be done is a group for hiding them...

**Comment by dreispt** [comment]
Is NUTS supposed to be part of the address? I understood that it was a classifier for statistical reporting. How is it currently being used in real life?

**Comment by pedrobaeza** [comment]
For example, in Spain there is a territory classification that is bigger than the state, but lesser than the country (comunidad autónoma). This is part of the address.

**Comment by dreispt** [comment]
In Portugal we also have "Autonomous Regions" (Madeira and Azores). They have their own government administration, including specific taxation (VAT an income Tax), similarly to Canarias, I believe. I always wondered if there is anything against representing them as "States".

Going on topic, I expected for NUTS to be used for legal and statistical reporting purposes. Also using it as Address elements sounds like a country specific. Is this also intended in the German localization?
What if I want to use NUTS classifiers but don't want them in the address?

**Comment by pedrobaeza** [comment]
No, it's not the same concept. I live in "Tomelloso", state "Ciudad Real", region "Castilla-La Mancha". The region "Castilla-La Mancha" contains 5 states (provinces): Ciudad Real, Toledo, Albacete, Guadalajara and Cuenca.

The same goes for Germany, where they have an intermediate territorial division (I don't remember the name, but I think they are the counts).

This territorial division is important for qualifying best the address and also for getting BI for that divisions: sales per region for example. So for me, the place is correct.

**Comment by dreispt** [comment]
I noticed that the 9.0 implementation provides a different, better, integration with the address fields. IMHO a backport should be considered.
