### ISSUE TITLE
[9.0][base_partner_merge] Unable to upgrade database once the module is installed

### ISSUE THREAD

**Issue by lmignon** [OCA/partner-contact#283]
Once the module is installed, I'm no  more able to update `-u all` my instance or restart the server.
The following error is raised by the server:

```
2016-06-21 11:48:50,626 26463 ERROR test-prod openerp.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/home/lmi/projects/odoo/odoo-test/src/odoo/openerp/modules/registry.py", line 386, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/lmi/projects/odoo/odoo-test/src/odoo/openerp/modules/loading.py", line 333, in load_modules
    force, status, report, loaded_modules, update_module)
  File "/home/lmi/projects/odoo/odoo-test/src/odoo/openerp/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/lmi/projects/odoo/odoo-test/src/odoo/openerp/modules/loading.py", line 132, in load_module_graph
    models = registry.load(cr, package)
  File "/home/lmi/projects/odoo/odoo-test/src/odoo/openerp/modules/registry.py", line 169, in load
    model = cls._build_model(self, cr)
  File "/home/lmi/projects/odoo/odoo-test/src/odoo/openerp/models.py", line 602, in _build_model
    hierarchy = type(name, (hierarchy, parent_class), {'_register': False})
  File "/home/lmi/projects/odoo/odoo-test/src/odoo/openerp/api.py", line 83, in __new__
    parent = type.__new__(meta, name, bases, {})
TypeError: Cannot create a consistent method resolution
order (MRO) for bases res.partner, ResPartner
```

**Comment by lmignon** [comment]
@yvaucher Do you encounter the same issue?

**Comment by yvaucher** [comment]
@lmignon just tried it and couldn’t reproduce. Are you sure you haven't installed `crm` beside this module?

I tried on OCB 808729f1f5a689f8b11310e9dd111806bd5dff01
Thus I tried again on last OCB commit 443ded9c7c2c254eb29fdd0cebf563ef58feeee2

Both worked fine.

Have you resolved it?

Note: my server has only few modules installed (37). Not even account, hr, sale nor stock is installed.

I tried to install sale and account modules and do an `-u all` again but no luck it's still working. :smile:

**Comment by cvinh** [comment]
@lmignon @yvaucher 
I did reproduce the problem. I noticed that I had both `crm` and `base_partner_merge` installed.
How would it be possible to avoid that situation ?

**Comment by yvaucher** [comment]
@invitu If you have `crm` installed, you don't need that module as it also exists in `crm`

Please read carefully the README: https://github.com/OCA/partner-contact/blob/10.0/base_partner_merge/README.rst

**Comment by cvinh** [comment]
@yvaucher I understand very well that the module is not needed when crm is installed.
BTW the problem that @lmignon and I meet is that if both modules are installed, the database is stuck and we cannot uninstall the module afterwards... (I had to manually uninstall the module by removing the folder in the server addons)
Do you think possible that the module would be "uninstallable" if crm is installed ? and that it would be uninstalled if crm is installed afterwards ?

**Comment by yvaucher** [comment]
@invitu I'm not aware of any way to forbid a module to be installed when an other is already present in database. Thought it could be possible to make a check in 
https://github.com/odoo/odoo/blob/9.0/openerp/addons/base/module/module.py#L399

**Comment by hbrunn** [comment]
I just talked to a colleague about this, and even though I can't invest time currently to fix this myself, here's how I think we can do it (and for the installation part: We can raise in one of the init hooks if the CRM module is installed)

The problem is that both modules being installed creates a class inheritance hierarchy where the same class is mentioned multiple times, very bad. To fix this, we can add a [`post_load` hook](https://github.com/odoo/odoo/blob/8.0/openerp/modules/module.py#L321-L322) which checks if both modules are installed, and remove the extra models from `base_partner_merge` from https://github.com/odoo/odoo/blob/8.0/openerp/models.py#L221 - if I have the order of stuff in mind correctly, this should avoid the models from `base_partner_merge` being constructed in the first place.
