### ISSUE TITLE
Readony on zip_id

### ISSUE THREAD

**Issue by open-net-sarl** [OCA/partner-contact#305]
The zip_id in partner view must be readonly as the zip or city.
<field name="zip" placeholder="ZIP" class="o_address_zip"
                                    attrs="{'readonly': [('type', '=', 'contact'),('parent_id', '!=', False)]}"/>
<field name="city" placeholder="City" class="o_address_city"
                                    attrs="{'readonly': [('type', '=', 'contact'),('parent_id', '!=', False)]}"/>
Because if it's not in readonly we can still modify zip and city with zip_id completion.

**Comment by pedrobaeza** [comment]
Please make the PR amending this.
