### ISSUE TITLE
[partner_address_street3] Suggestion to add street3 field in address_format using post_init_hook and uninstall_hook

### ISSUE THREAD

**Issue by atchuthan** [OCA/partner-contact#308]
@gurneyalex 

The field is only available in res.partner form and is not shown in name_get of show_address at Sale order nor in its report.

So, I am planning to create post_init_hook for this module, to add street3 in the address format of each country via SQL query.

**post_init_hook query**
UPDATE res_country
SET    address_format = replace(address_format, '%(street2)s', E'%(street2)s\n%(street3)s')

**uninstall_hook query**
UPDATE res_country
SET    address_format = replace(address_format, E'\n%(street3)s', '')

Let us know your opinion

**Comment by gurneyalex** [comment]
sounds like a good idea to me.

**Comment by atchuthan** [comment]
thanks.. will try to make the PR in few days

**Comment by atchuthan** [comment]
created PR https://github.com/OCA/partner-contact/pull/316 related to this issue

**Comment by AKSHAYAGOVIND** [comment]
Hi,

I am using the Odoo 12.0 enterprise version. I  imported the partner_address_street3 module. But i am getting the below error.

-------------------------------------------------------------------
ValueError: Field `street3` does not exist

Error context:
View `res.partner.form`
[view_id: 113, xml_id: base.view_partner_form, model: res.partner, parent_id: n/a]
-----------------------------------------------------------------------
Please help me how to resolve this issue. I am getting the same error when I try to import the partner_contact_Gender module as well.  I have attached my error report.

![image](https://user-images.githubusercontent.com/43378529/55417589-9d781b80-5536-11e9-9000-3649f24bc55d.png)
