### ISSUE TITLE
Modulo base_location improvement discussion

### ISSUE THREAD

**Issue by FrancoTampieri** [OCA/partner-contact#33]
Hi!

I'm analyzing the base_location module, and I noticed with my customers that the better_zip field is cool but in the actual implementation is "redundant" in tha partner profile as you can see in the image below:

![screenshot 2014-09-22 13 23 59](https://cloud.githubusercontent.com/assets/4396444/4355402/7c4ac488-424b-11e4-8874-54d42b9e4c74.png)

The city, zip, state and country information is proposed twice and in my opinion is not the best choice.

So what do you think to remove the m2o field and put a button with a function that set the right parameter in the res.partner?

What do you think about?

My 2 cents

Regards

Franco

**Comment by pedrobaeza** [comment]
Hi, Franco,

This is a discussion we already have, and on the contrary, I don't think
it's redundant. You have that zip field as an "autocomplete wizard", but we
don't need to force everyone to create a state and city and fill them in
the model to complete an address, so this way you have the alternative to
put freely anything you want in the other fields.

Maybe we can hide it on view mode...

Regards.

2014-09-22 13:32 GMT+02:00 Franco Tampieri notifications@github.com:

**Comment by FrancoTampieri** [comment]
Hi Pedro,
unfortunately I have not followed the debate from the beginning. However, even just view the file in edit mode is a good idea, if there is no objection I made the change and make a PR

Regards

**Comment by pedrobaeza** [comment]
OK, do it and we can follow the discussion there.

Regards.

2014-09-22 16:14 GMT+02:00 Franco Tampieri notifications@github.com:
