### ISSUE TITLE
partner_firstname name splitting

### ISSUE THREAD

**Issue by lasley** [OCA/partner-contact#332]
The default operation of [`partner_firstname`](https://github.com/OCA/partner-contact/tree/10.0/partner_firstname) is to split names as LastName Firstname, but this is weird from a user perspective. This design caused incorrect splits on 100% of my customer data, so I don't see how it's useful. The note in the ReadMe implies that it's not intended to be accurate, but then why have it?

Would a fix be accepted to make this a bit smarter? I'm not sure if this logic goes international but in America if last name is intended to be first, a comma is appended after it `Lastname, Firstname`. 

My proposal is to `.endswith` on what is currently being split into the `Lastname` col. If the string ends with a `,`, it is correctly split. Otherwise, reverse the split to `Firstname Lastname`.

The same logic would be added to the inverse, adding a `,` between the Lastname and the Firstname on display of the full name.

My other alternative is to simply make a downstream module to handle this, but I feel that this should be in core.

**Comment by hbrunn** [comment]
well, historically, this module comes from French speaking contributors, where this splitting is correct - also without a comma. "BRUNN Holger" is a totally normal French way to give a name. For the Netherlands, we fix this in a module depending on it https://github.com/OCA/l10n-netherlands/blob/8.0/l10n_nl_partner_name/model/res_partner.py#L62. From this, you'd only need an init hook the overwrites what `partner_firstname` did with what your local concept of correct name splitting is. That should be doable by simply calling the init hook again in your own post init, then the necessary changes are already done.

**Comment by lasley** [comment]
Interesting so in France there is no way to differentiate whether the name is last first, or is it the fact that the last name is capitalized?

Awesome thanks for the suggestion @hbrunn - this actually makes me understand exactly what the `l10n` OCA repos are for too. It also seems you've already written most of my code for me, so thats nice too! Even included `initials`, which I also needed ❤️ 

I'll submit a PR to the l10n-usa. Thanks again, closing.

**Comment by pedrobaeza** [comment]
We covered other orders with this PR: https://github.com/OCA/partner-contact/pull/227, because in Spain that order is not always the desirable.

**Comment by lasley** [comment]
Well crap guess I should close OCA/l10n-usa#4 then. Looks like I will instead need to forward-port the changes, seems they didn't make it to the versions I care about 😦
