### ISSUE TITLE
[ROADMAP] partner_contact_nutrition_activity_level

### ISSUE THREAD

**Issue by max3903** [OCA/partner-contact#346]
# Version 9.0.2.0.0

Change activity level to be a Many2one field to a new model (partner_contact_activity_level) with the default data already loaded.

**Comment by max3903** [comment]
ping @susport

**Comment by lasley** [comment]
I was about to handle this in the v10 migration, but this seems a bit excessive IMO. What about a method to return the select options instead? Happy medium?

Are there some use cases that you can elaborate on that I'm maybe not thinking of?

**Comment by dreispt** [comment]
Hello, I just noticed all the nutrition related modules, and just realized that they are health/diet related.
(I initially thought they were related to lead generation...)
I think partner-contact should be related to business relations, partner localization requirements, addresses, etc.
Diet and health related modules would be best in their own repo.
Thoughts?

**Comment by lasley** [comment]
👍  for `vertical-health`. I'm having a ton of trouble offloading modules from `vertical-medical` (we broke the 50 count in the incubator the other day). A new repo would help immensely.

**Comment by dreispt** [comment]
@lasley That sounds good to me. I too agree that there is no need to overload `vertical-medical`.

**Comment by lasley** [comment]
I'll shoot the request to mailing list once we gather stakeholder thoughts.

@max3903 - these nutrition modules are your babies. Thoughts on inclusion into a different repo?

**Comment by max3903** [comment]
@Lasley I don't mind at all. I am using the package from wheelhouse.odoo-community.org

**Comment by dreispt** [comment]
@max3903 honoring stable module releases, this repo change could be only for 10.0
