### ISSUE TITLE
[RFC] partner_rating: Rating Aggregation By Partner

### ISSUE THREAD

**Issue by lasley** [OCA/partner-contact#407]
This module will provide an attribute on partners to represent their overall rating across all source record types.

It will do this by adding a `rating_ids` o2m field with an inverse pointing to `rating.rating.rated_partner_id`. A computed field `all_rating_ids` will be added that will represent all ratings for the partner including the ratings for all children (and subchildren).

Another computed field, `rating` will also be added that will compute the average `rating_ids.rating` for the partner. `all_rating` will do the same thing for `all_rating_ids`. 

It will also need a visual representation of the partner's rating in the following locations:
* Partner Kanban - As an icon (like opportunities and sales), using a 😄  icon, and a percentage for the rating
* Partner Form View - As a smart button, using a 😄  icon, and a percentage for the rating. Clicking the button takes you to the `rating_ids` in form view
* Partner List View - As a percentage in a column to the far right

There will be a setting at the partner level defining whether their displayed rating in the views includes children (`all_rating`) or if it is just for the partner themselves (`rating`). This option will default to correspond with the parent record, or to `all_rating` if there is not a parent.

At some point we will probably also make a glue module so that if `website_partner` is installed, the rating is displayed on the partner profile page.

Does anyone know of any pre-existing code or strategy we can start from, or notice anything wrong in the plan?

**Comment by lasley** [comment]
Alright now this is actually ready, instead of my accidental early submission! Can a PSC please mark as `question` and `10.0` milestone? Thanks!

**Comment by rafaelbn** [comment]
Have you check rating* modules from Odoo? Maybe same concept applied to the res.partner?

**Comment by lasley** [comment]
@rafaelbn - Yeah this is actually to complement those modules.

Imagine a scenario where `rating_issue` is installed, plus a hypothetical `rating_appointment`. A partner can receive ratings on two different types of records, issues and appointments, so this will provide an aggregation between them onto the partner itself.

Edit/Note: You will not actually rate a partner with this module. It will instead use ratings derived from other `rating_*` modules (`rating.rating` model).
