### ISSUE TITLE
[10.0] partner_identification: Infinite loop for _search_identification

### ISSUE THREAD

**Issue by moylop260** [OCA/partner-contact#434]
The following test has a [search](https://github.com/OCA/partner-contact/blob/1bc94dff59c405c4ac6c3eecb6ff2499accfacb1/partner_identification/tests/test_res_partner.py#L123) with a infinite loop computing the domain from [odoo/osv/expression.py#L781](https://github.com/odoo/odoo/blob/79477b8d96be47cca5609ce5e4dd84a7e7f64f0a/odoo/osv/expression.py#L781)

`category_id.code='SSN'` increase for each iteration of the loop:
![screen shot 2017-06-01 at 12 11 13](https://cloud.githubusercontent.com/assets/6644187/26691178/cececcc2-46c1-11e7-9807-fe7f2b3cdc47.png)

There is a issue using the following field:
https://github.com/OCA/partner-contact/blob/1bc94dff59c405c4ac6c3eecb6ff2499accfacb1/partner_identification/tests/test_res_partner.py#L13-L23

And using the following method:
https://github.com/OCA/partner-contact/blob/1bc94dff59c405c4ac6c3eecb6ff2499accfacb1/partner_identification/models/res_partner.py#L139

More info about: https://github.com/OCA/maintainer-quality-tools/issues/448#issuecomment-305477622

PR related
https://github.com/OCA/partner-contact/pull/419

**Comment by yajo** [comment]
Thanks @moylop260! Great debugging!

Hi there @lasley, do you think you can fix this, given https://github.com/OCA/partner-contact/pull/419 was yours?

**Comment by pedrobaeza** [comment]
@lasley any news about this bug?

**Comment by lasley** [comment]
Been in and out of town (Pycon + a vacation), so wasn't able to hit this yet. I'm starting to catch up on workload though, so I should have something here soon.
