### ISSUE TITLE
[9.0] Uncaught Error: Unknow field parent_id in domain [["type","=","contact"],["parent_id","!=",false]]

### ISSUE THREAD

**Issue by VisiionSoluciones** [OCA/partner-contact#439]
Hi,
I have this error when I try to create a new contact inside a partner.

I think the problem may be in the following file:

base_location/views/partner_view.xml

in attrs values

**Comment by StefanRijnhart** [comment]
Solved in https://github.com/OCA/partner-contact/commit/3496517550ee1b
