### ISSUE TITLE
[10.0] partner_firstname: Firstname Lastname order not correctly changed.

### ISSUE THREAD

**Issue by woodbrettm** [OCA/partner-contact#443]
1. Initial config: Lastname, Firstname
2. Go to Settings => General Settings
3. Change config to Firstname, Lastname
4. Hit Recalculate Names, then click apply
5. Go back to contact. I think the name field changes from Phillip Miller to Miller Phillip, however notice the firstname and lastname fields.
![phillip](https://user-images.githubusercontent.com/11901801/27711103-f671e8f6-5cd6-11e7-8f35-4b02af94dacd.jpg)

@lasley

**Comment by jeroenev** [comment]
logic for when recalculate button appears is messed up
change the value -> button shows up (but value is NOT yet saved)
click button -> recalculates based on saved value (which is not the value currently on the view)
press save -> page refreshes -> recalculate button is gone
so you have to basically press save, and then immediately after (before the page refresh) press recalculate, then it works correctly (or just remove the invisible attribute on view, then you can just press it after save and refreshing page)
EDIT: same for version on odoo11 btw, this is for odoo11 but i'm assuming it's the same in odoo10

**Comment by pedrobaeza** [comment]
Closing as answered

**Comment by jeroenev** [comment]
I wouldn't considder this answered, as the logic for when the button appears is clearly not working as intended, maybe i missed something where they fixed it but aside from that this should still be addressed

You have a 1 to 2 second window where you can press the button to make it do the right calculation, clearly not what it's supposed to be like

**Comment by pedrobaeza** [comment]
OK
