### ISSUE TITLE
fatal: No url found for submodule path 'pylint-odoo' in .gitmodules

### ISSUE THREAD

**Issue by shepilov-vladislav** [OCA/partner-contact#448]
```
~ » git clone --recursive https://github.com/OCA/partner-contact.git -b 10.0                                                              vladislavshepilov@Vladislavs-MacBook-Pro
Cloning into 'partner-contact'...
remote: Counting objects: 17718, done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 17718 (delta 5), reused 5 (delta 3), pack-reused 17689
Receiving objects: 100% (17718/17718), 5.68 MiB | 1.12 MiB/s, done.
Resolving deltas: 100% (12862/12862), done.
fatal: No url found for submodule path 'pylint-odoo' in .gitmodules
```

**Comment by yajo** [comment]
Not sure how did that submodule land there without a `.gitmodules` file...

**Comment by pedrobaeza** [comment]
It's not an issue of this project.

**Comment by yajo** [comment]
Yes it is, you can check the existence of the dangling submodule by browsing the 10.0 tree in github, it seems to have been added here: https://github.com/OCA/partner-contact/commit/1a0000c184b8854e1d29fb91922a5f4fa701cc35#diff-43132dc343f29dbe8e58462f7dd46d91

**Comment by pedrobaeza** [comment]
Ouch, please remove it via direct commit.

**Comment by yajo** [comment]
I tried, but I couldn't, not sure how to do that...

**Comment by Rayito-M** [comment]
I tried to fix it but can't do a direct has i don't have the writing right on the repro

CAn you try to fix it now as it's really a 2mn job...

Best

**Comment by yajo** [comment]
If you have the fix @ChristopheCubat, can you PR?
