### ISSUE TITLE
[11.0] New branch

### ISSUE THREAD

**Issue by Ehtaga** [OCA/partner-contact#453]
When do you think the 11.0 branch will be available on OCA repos? We are starting to migrate some modules and would be glad to create some PR towards a 11.0 branch.

Thanks

**Comment by pedrobaeza** [comment]
Sorry, but branches are created only when official release is done (usually at the Odoo days). I also recommend not to invest too much time on 11.0 migrations yet, as things can change a lot and to be a futile effort.
