### ISSUE TITLE
partner_relations module / left and right partners mismatch/  - corrupting relations and throws "Partners cannot have a relation with themselves"

### ISSUE THREAD

**Issue by christophe-hanon** [OCA/partner-contact#454]
The partner_relations module exhibits a series of incorrect behaviors.ra

This problem is reported for version 8, but as far as I can see, the next generation module has changed its name but not its behavior....

In my case we have defined the relation 'tta_member' with the inverse 'has_tta_member'.

# Case 
A has_tta_member B1
A has_tta_member B2

# Problem 1

From the record A / click on 'relations' and you see both relations. Attempting to edit record B1 or B2 - for example updating the phone number of B1 -
will generate an exception : "Partners cannot have a relation with themselves"

Looking inside the code, indeed the comparisons is done between the 2 same ids.... strange

# Problem 2

Try to change the relation with B2 and put B3 instead results in the following incorrect relation :+1: 

B3 has_tta_member A

Instead of A has_tta_member B3

# Some code remarks

First the code convert this / other into left /right partners. But in most cases only one partner is modified. That's the main reason for my first problem.

Second problem I think is :     

```
 if 'type_selection_id' not in vals:
            return vals 
```

In most cases the the type is not changed and because of the return the inversion code is not reachable.

Sorry to say, but as such the code looks dangerous to me, resulting in data corruption....

I did a quick fix - not very clean but I don't know enough  the module and I am short on time

````

    @api.model
    def _correct_vals(self, vals):
        """Fill left and right partner from this and other partner."""
        vals = vals.copy()
        if 'this_partner_id' in vals:
            vals['left_partner_id'] = vals['this_partner_id']
            del vals['this_partner_id']
        if 'other_partner_id' in vals:
            vals['right_partner_id'] = vals['other_partner_id']
            del vals['other_partner_id']
        # in most cases type_selection_id is not in the vals....
        if 'type_selection_id'  in vals:  
            selection = self.type_selection_id.browse(vals['type_selection_id'])
            type_id = selection.type_id.id
            del vals['type_selection_id']
        else:
            selection = self.type_selection_id
            type_id = selection.type_id.id
        is_inverse = selection.is_inverse
        vals['type_id'] = type_id
        # Need to switch right and left partner if we are in reverse id:
        if 'left_partner_id' in vals or 'right_partner_id' in vals:
            # print "Inversing"
            if is_inverse:
                left_partner_id = False
                right_partner_id = False
                if 'left_partner_id' in vals:
                    right_partner_id = vals['left_partner_id']
                    del vals['left_partner_id']
                if 'right_partner_id' in vals:
                    left_partner_id = vals['right_partner_id']
                    del vals['right_partner_id']
                if left_partner_id:
                    vals['left_partner_id'] = left_partner_id
                if right_partner_id:
                    vals['right_partner_id'] = right_partner_id
              
        return vals

    @api.multi
    def write(self, vals):
        """divert non-problematic writes to underlying table"""
        print "res_partner_relation_all BEFORE %s" %vals
     
        for rec in self:
            cvals = vals.copy()
            # need to take the other side of the relation in case we need 
            # exchanging the side....
            if 'this_partner_id' in cvals and \
               'other_partner_id' not in cvals :
                   cvals['other_partner_id'] = rec.other_partner_id.id
            elif 'other_partner_id' and 'this_partner_id' not in cvals :
                   cvals['this_partner_id'] = rec.this_partner_id.id
            fvals = self._correct_vals(cvals)
            print "res_partner_relation_all AFTER %s" %fvals
        
            rec.relation_id.write(fvals)
        
        return True
``

**Comment by christophe-hanon** [comment]
One thing sure the problem is still there in 10.0. Please note that if you enable symetric relation, data can be corrupted.

**Comment by pedrobaeza** [comment]
@hbrunn are you aware of this?

**Comment by hbrunn** [comment]
no, I'm not. there are a couple of [PRs on this module](https://github.com/OCA/partner-contact/pulls/NL66278) by @NL66278, did you encounter said issue there?

**Comment by NL66278** [comment]
@hbrunn I can confirm that I have seen these errors as well. They are tackled in my PR's on the 10 branch. Should be easy to backport these changes to 8.0 / 9.0.
