### ISSUE TITLE
partner_address_street3

### ISSUE THREAD

**Issue by alexis-via** [OCA/partner-contact#46]
In the module partner_address_street3:

In model/partner.py, there is:

```
    def _commercial_fields(self, cr, uid, context=None):
        fields = super(res_partner, self
                       )._commercial_fields(cr, uid, context=context)
        fields.append('street3')
        return fields
```

Street3 is not a commercial field, so this code should not exists.

BUT street3 is an address field, that needs to be synced when you activate "Use parent address" ; for that, the following code is required:

```
    def _address_fields(self, cr, uid, context=None):
        '''Add street3 in sync of address when you say "Use company address"'''
        res = super(res_partner, self)._address_fields(
            cr, uid, context=context)
        res.append('street3')
        return res
```

I'll do a PR to fix this when I have time.

**Comment by nbessi** [comment]
Fix here https://github.com/OCA/partner-contact/pull/47
