### ISSUE TITLE
10.0 No translations in Transifex

### ISSUE THREAD

**Issue by hhgabelgaard** [OCA/partner-contact#466]
All resources (addons) have 0 source strings in transifex for the 10.0 branch:

![image](https://user-images.githubusercontent.com/7933710/29907336-29e7ba74-8e1b-11e7-9df5-239ffce13f5d.png)

Other branchs (8.00, 9.0) seems ok.

Maybe related: The .pot file in partner_contact_gender is wrongly named (https://github.com/OCA/partner-contact/blob/10.0/partner_contact_gender/i18n/partner_gender.pot) and last change is 2 year old - I would assume it should be updated by Travis?

**Comment by pedrobaeza** [comment]
It should be handled now.
