### ISSUE TITLE
[10]: partner_street_name: 130k of Customer Data makes migration process stuck

### ISSUE THREAD

**Issue by Derter** [OCA/partner-contact#516]
Installation process calls the migration of street into street and housenumber. On 130k Customer entries it does not install. 

The process stops at any point and does not go through. When you stop odoo, process gets stuck.

When you go with "python odoo-bin -c /etc/odoo.conf -u partner_street_number --stop-after-init" you cannot even end process with keyboard command (ctrl+c). You can only kill it

**Comment by pedrobaeza** [comment]
The problem is performance and timeouts set on your deployment. You can try to propose an improvement over the computation, but there's no bug at all.
