### ISSUE TITLE
Problem with Italian localization.

### ISSUE THREAD

**Issue by lucalg74** [OCA/partner-contact#536]
module: base_location_geonames_import
version: 9.0

**Steps to reproduce**
- ...

**Current behavior**
I have imported without any error all cities and relative provinces. In some of them i have REGION instead Province. I've searched on the source and dounloaded the file for Italy. Opened on Excel i see everything correct. So, seems that a problem occurs on data import.

**Expected behavior**

**Comment by eLBati** [comment]
Hello @lucalg74 which specific province does this happen with? Does it only happen  in version 9? Thanks

**Comment by lucalg74** [comment]
Hi, with a lot of provinces... Lazio, Campania, sud Sardegna, lombardia

Il 22 dic 2017 08:30, "Lorenzo Battistini" <notifications@github.com> ha
scritto:

**Comment by FrancoTampieri** [comment]
I haven't this problem on release 10.0 tested on two new test instances in Kubernetes

**Comment by pedrobaeza** [comment]
The problem is to not install https://github.com/OCA/l10n-italy/tree/9.0/l10n_it_base_location_geonames_import
