### ISSUE TITLE
[10.0] partner_label report

### ISSUE THREAD

**Issue by benwillig** [OCA/partner-contact#556]
### Steps to reproduce:
1) Go on the partner list view
2) Select all partners
3) Print Partner label report

### Current behavior:
The reports looks fine but some labels are displaced. To be able to see it, I added a border to the address block.

### Expected behavior:
All labels should be aligned.

![screenshot from 2018-02-07 13-15-24](https://user-images.githubusercontent.com/27724417/35916037-53789b8a-0c09-11e8-96ff-f3e563a98f90.png)

![screenshot from 2018-02-07 13-15-34](https://user-images.githubusercontent.com/27724417/35916049-5b3ec970-0c09-11e8-8b38-cf1a87312ae1.png)

As you can see in the last screenshot, there is a gap between "ASUSTeK, Peter Mitchell" and "Bob Egnops". Also between "ASUSTeK, Tang Tsui" and "China Export".

**Comment by benwillig** [comment]
@hbrunn as you are the author of the module, you might have an idea. But I'm trying to find a fix at the moment.

**Comment by rafaelbn** [comment]
Fixed in https://github.com/OCA/partner-contact/pull/557
