### ISSUE TITLE
nuts region and Better ZIP can work better together 

### ISSUE THREAD

**Issue by icf20** [OCA/partner-contact#562]
currently placing the zip code with better zip installed, for example 28821, will auto fill the NUTS L1 to Spain, is quite nice but the system should also auto fill NUTS L4 because is know(madrid)

![image](https://user-images.githubusercontent.com/17784575/36202360-cc93eb12-1183-11e8-96a7-a0930f1d29fc.png)

**Comment by pedrobaeza** [comment]
There's no direct correspondence. If you develop an integration module, it's welcome.

**Comment by icf20** [comment]
for the record i leave this here 

![image](https://user-images.githubusercontent.com/17784575/36631459-61d3a14e-1978-11e8-9adf-50eac9f47d86.png)

i do think this could work better with l10n_es_toponyms
