### ISSUE TITLE
Problem version 11

### ISSUE THREAD

**Issue by juannmagd** [OCA/partner-contact#593]
Al intentar elegir un contacto ya existente se obtiene este error
×
Odoo Server Error - Error de acceso
No se ha podido completar la operación por restricciones de seguridad. Contacte con su administrador del sistema.

(Tipo de documento: res.partner, Operación: read)

**Comment by juannmagd** [comment]
El usuario es el administrador y he hecho las pruebas con solo el modulo de contactos instalado

**Comment by pedrobaeza** [comment]
Please:

* In English.
* Specify module.

I close this issue for you to make a proper one.
