### ISSUE TITLE
[11][base_location_geonames_import] Close button or close dialog after importing.

### ISSUE THREAD

**Issue by SalahAdDin** [OCA/partner-contact#595]
I found this module very very useful, thank you.

I'm thinking about put a close button or dialog after importing could be more clear the importing workflow for normal users. Also,  it could be great a window reload, it will make clear to the user that all localization where imported successful. 

What do you think about?

**Comment by pedrobaeza** [comment]
Which module?

**Comment by SalahAdDin** [comment]
I'm sorry, i added now.

**Comment by pedrobaeza** [comment]
The dialog auto-closes already. I think you have a timeout in your reverse proxy that causes this.

**Comment by SalahAdDin** [comment]
@pedrobaeza can you explain me it please? if you are available.

**Comment by pedrobaeza** [comment]
I repeat my sentence:

> I think you have a timeout in your reverse proxy that causes this.

The rest depends on your configuration, your reverse proxy (Nginx, Apache...), but this is out of the scope of here.

**Comment by SalahAdDin** [comment]
Is there in the documentation? How can test it?

**Comment by SalahAdDin** [comment]
@pedrobaeza Yes, i tested it and i have no problem without proxy, but i don't know why i have a problem with proxy: `Failed to load resource: the server responded with a status of 504 (Gateway Time-out) /web/dataset/call_button:1 `

It happens in local production environmentm we did not deploy it in server.

**Comment by pedrobaeza** [comment]
You have to put a higher timeout on the reverse part, but this out of the scope of the help I can provide
