### ISSUE TITLE
[11.0][base_location_geonames_import]504 (Gateway Time-out) importing USA

### ISSUE THREAD

**Issue by SalahAdDin** [OCA/partner-contact#598]
Hello guys,

I'm using this module to pre-populate the database with address information.
I successfully imported Turkey, Spain and Germany, without any problem, but i get the next error importing USA:
`jquery.js:9631 POST http://localhost/web/dataset/call_button 504 (Gateway Time-out)`
It is relate to this other [error](https://github.com/OCA/partner-contact/issues/595).

I change the `timeout` settings in my configuration file to:
```nginx
proxy_connect_timeout 600;
proxy_send_timeout 600;
proxy_read_timeout 600;
```

It works fine for countries with few zip codes, it is my conclution.

But i want your help for clarify this issue.

Thank you

**Comment by pedrobaeza** [comment]
You might not restart proxy or something, as the problem is clear.
