### ISSUE TITLE
test_base_location_geonames_import depends on download.geonames.org

### ISSUE THREAD

**Issue by ap-wtioit** [OCA/partner-contact#624]
The tests for geonames import depend on the download server for geonames.

This is a problem because running tests in runbot causes them a lot of traffic. Currently there is an error on their server that breaks the tests.

http://download.geonames.org/export/zip/ is missing MC.zip (which is needed for the tests)
from http://download.geonames.org/export/dump/alarm_1535933897045.log i guess they are doing maintenance (hopefully)

I guess the test should not depend on an external server being up and well.

Info @wt-io-it

**Comment by pedrobaeza** [comment]
That's on purpose, for detecting when Geonames service is down, as the main purpose of this module is to download the files from there. There's not too much traffic, as we are downloading the smallest file.

**Comment by ap-wtioit** [comment]
@pedrobaeza i think using tests for monitoring is really a bad idea, as it obviously produces false positives and therefore may lead to people not taking tests seriously.

**Comment by pedrobaeza** [comment]
It's not only a monitoring task, but also to detect changes in the format of the files. The main purpose of the module is that one. Mocking it will fake real errors.

**Comment by ap-wtioit** [comment]
@pedrobaeza thanks for clarifying, i see your point there and i probably would detect format changes the same way.
