### ISSUE TITLE
External ID not found in the system: base.res_partner_4

### ISSUE THREAD

**Issue by Alexandre-Bernardes** [OCA/partner-contact#629]
I have this error when I try to install:

File "W:\Odoo\Odoo 11.0\server\odoo\addons\base\ir\ir_model.py", line 1323, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: base.res_partner_4

any idea whats happened?

**Comment by pedrobaeza** [comment]
You are installing the module with demo data, but that demo data is not present (it has been deleted). Install it in a fresh database or without demo data.

**Comment by Alexandre-Bernardes** [comment]
thanks
