### ISSUE TITLE
[8.0] [base_partner_sequence] Add config options to make "reference" field unique and required

### ISSUE THREAD

**Issue by matteotrubini** [OCA/partner-contact#64]
In our current software we have a field "partner number" with which we identify uniquely partners.
This module can help us to replicate this, but it currently allows:
- to leave the field blank on modify
- to enter a value already used for another partner
  Do you think that add this config options could be an improvement? At a first look it should not be a complex task.

**Comment by NL66278** [comment]
Your second requirement is in the current OCA branches satisfied with the partner_ref_unique module.

If you want to make ref required, this might also be made into another module.
