### ISSUE TITLE
[11.0] partner_phone_search name_search override bug

### ISSUE THREAD

**Issue by j-zaballa** [OCA/partner-contact#665]
https://github.com/OCA/partner-contact/blob/8216b16a0a554bc7eec4b4fcaec339641c7c8f3c/partner_phone_search/models/res_partner.py#L14

### Current Behavior
name_search override calls to super and has a return if `name` evaluates to `True`. Whenever name is an empty string, an error occurs.

### Expected Behavior
name_search should always return the list of tuples it is expected to return, even if `name` is an empty string.

**Comment by nikul-serpentcs** [comment]
@j-zaballa I think here if `name` is empty then return all the record.

I tried in my local, I passed empty string in partner then return this...

`-----------name_search--------------- [(8, 'ASUSTeK'), (13, 'Camptocamp'), (10, 'China Export'), (11, 'Delta PC'), (45, 'My Company, Chicago'), (19, 'Agrolait, Edward Foster'), (20, 'ASUSTeK, Arthur Gomez'), (18, 'ASUSTeK, James Miller')]`

@pedrobaeza Can you please help here.

**Comment by pedrobaeza** [comment]
Overwriting `name_search` is always tricky. Check https://github.com/OCA/l10n-spain/blob/d21c45868a8efcce106703b35bf9a52a254b64de/l10n_es_partner/models/res_partner.py#L39 for the most compatible way I have found to override it.
