### ISSUE TITLE
[10.0] Cannot update "default user" after installing "partner_firstname"

### ISSUE THREAD

**Issue by protontrigg3r** [OCA/partner-contact#671]
With _partner_firstname_ the fields _First Name_ and _Last Name_ are mandatory, then it is no longer possible to update the _default user_ (**_Settings > General settings > New user access rights > Related partner_**).

**Comment by pedrobaeza** [comment]
I don't see why can't you edit it, as last name is the only required one, and it's mapped to the normal name.

**Comment by protontrigg3r** [comment]
The values ​​of this fields are empty for **_default user_** object. And they should remain empty, from my point of view.

**Comment by pedrobaeza** [comment]
Exactly, but I still don't see the problem. You fill any of them, and the rest is populated automatically. If you fill name, then last_name is brought with that value.

**Comment by protontrigg3r** [comment]
Suppose you **only** want to set Italian language for new partners. You can not do it, because:

- you go in _Settings > General settings > New user access rights > Related partner_
- you set _Language_ filed to _Italian_
- you click _Save_ button
- Odoo refuse to save because mandatory fileds _Last Name_ a _First Name_ are missing

**Comment by pedrobaeza** [comment]
But when you install the module, all existing records are update and `last_name` field is populated, so this can't happen.
