### ISSUE TITLE
add @NL66278

### ISSUE THREAD

**Issue by hbrunn** [OCA/partner-contact#698]
I propose to add @NL66278 to the PSC

Merged contributions:
https://github.com/OCA/partner-contact/graphs/contributors?from=2013-06-23&to=2019-01-26&type=a

PRs:
https://github.com/OCA/partner-contact/pulls/NL66278

CC @OCA/board

**Comment by pedrobaeza** [comment]
+1 for me, but I think this should go in OCA contributors list.

**Comment by hbrunn** [comment]
wrote the mail, so I'll close this
