### ISSUE TITLE
location completion get stuck when used v12

### ISSUE THREAD

**Issue by icf20** [OCA/partner-contact#701]
**related to base_location_geonames_import**

steps 

1 edit some contact zip code
2 go to the next contact and type some zip code 

![image](https://user-images.githubusercontent.com/17784575/52201309-60134c80-286b-11e9-94b0-fd962ee782d7.png)

you see that the zip code displayed are very few and are similar to those used before

workaround

before editing the contact  press ctrl+F5
![image](https://user-images.githubusercontent.com/17784575/52201440-b1bbd700-286b-11e9-9a37-f1fddb9992ee.png)

**Comment by pedrobaeza** [comment]
Are you clicking in "Search more..."?

**Comment by icf20** [comment]
> Are you clicking in "Search more..."?

yes

**Comment by pedrobaeza** [comment]
Well, then it's Odoo behavior. Nothing related to `base_location_geonames_import`. Any way, this is the expected one, as Odoo filters this window before showing it according previous typing.
