### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by lfreeke** [OCA/partner-contact#708]
It seems that weblate is not pushing translation to the 10.0 branch, the last commit was Dec 9, 2018.

I did some translation last week for partner_identification but I don't see a commit for it. 

What can I do to solve this?

**Comment by pedrobaeza** [comment]
@sbidoul can you please check this?

**Comment by sbidoul** [comment]
@lfreeke weblate the weblate job scheduler was down apparently. I restarted and pushed changes to this repo manually.

**Comment by lfreeke** [comment]
Thank you @sbidoul
