### ISSUE TITLE
[10.0] partner_contact_nationality

### ISSUE THREAD

**Issue by i-vyshnevska** [OCA/partner-contact#709]
My question about module [partner_contact_nationality](https://github.com/OCA/partner-contact/tree/10.0/partner_contact_nationality), AFAIN nationality is more wider concept then country, one country could have a lot of nationalities like China, or nationality without country, so it should be linked to new model and dataset of nationalities could be loaded.

**Comment by pedrobaeza** [comment]
Well, I suppose this was a simplification. Do we have any source of all the existing nationalities? Maybe a Python library? That can go to OCA/community-data-files.

**Comment by simahawk** [comment]
https://pypi.org/project/pycountry/ to name one

**Comment by i-vyshnevska** [comment]
I misinterpreted notion nationality and ethnos
