### ISSUE TITLE
Installing version 12 branch onto odoo.sh results in failed unit test

### ISSUE THREAD

**Issue by mdodgeco** [OCA/partner-contact#718]
I've just installed the v12 Partner Affiliates app onto a clean development branch in odoo.sh and it causes the unit tests to fail with the attached errors. I installed that app into odoo.sh from the app store. I've also tried installing the entire partner_contact repo via odoo.sh "submodule add" on a seprate development branch, and the unit tests fail in the same manner. Any ideas?

![error](https://user-images.githubusercontent.com/48109491/54649340-2e072400-4a80-11e9-8b6f-3f9302a34ac8.png)

**Comment by pedrobaeza** [comment]
The failed test is not of this module.
