### ISSUE TITLE
[8.0] partner_firstname, name with store=True are not recompute during the copy

### ISSUE THREAD

**Issue by jssuzanne** [OCA/partner-contact#72]
This error is only view with the res.users.
# 
## FAIL: test_copy_user (partner_firstname.tests.test_partner_firstname.test_partner_firstname)

Traceback (most recent call last):
  File "/Users/jssuzanne/openerp/sensee/ecommerce/partner_contact/partner_firstname/tests/test_partner_firstname.py", line 94, in test_copy_user
    'Copy of the user failed with wrong name'
AssertionError: u'lastname firstname firstname' != 'lastname (copy) firstname' : Copy of the user failed with wrong name

launch with the anybox.testing.openerp. I saw that the name is removed of the default values in the method copy_data. But the name must be force to None to be recompute, because with store=True the fields.function isn't be recompute.

**Comment by yvaucher** [comment]
Confirmed by Travis

**Comment by StefanRijnhart** [comment]
Fixed upstream in https://github.com/odoo/odoo/commit/3a44d84b0f0dd7a0596f4854652391538e7a764e
