### ISSUE TITLE
ValueError: Field `gender` does not exist

### ISSUE THREAD

**Issue by AKSHAYAGOVIND** [OCA/partner-contact#725]
Hi,

The personal page information module was installed successfully. But when I tried to install partner_contact_gender in my odoo 12.0. I got the error "Error while validating constraint\n\nField `gender` does not exist\n\n". Attached the error report.
![image](https://user-images.githubusercontent.com/43378529/55418503-6acf2280-5538-11e9-9087-1f0bcb1078ac.png)

Also when i try to access my contact app I encounter an odoo server error " ValueError: Field `gender` does not exist"

Error context:
View `res.partner.form`

Attached below as well.
[view_id: 113, xml_id: base.view_partner_form, model: res.partner, parent_id: n/a]

![image](https://user-images.githubusercontent.com/43378529/55418548-863a2d80-5538-11e9-911e-fbcbd60fc94a.png)

I dunno what i am missing . Please help me out

**Comment by pedrobaeza** [comment]
Restart your Odoo service.

**Comment by AKSHAYAGOVIND** [comment]
Hi Pedrobaeza,

Even after i restarted the odoo service. I got the same error

**Comment by pedrobaeza** [comment]
Sorry, but this is working properly, so it's an unknown deployment problem. You can test it in runbot:

https://runbot.odoo-community.org/runbot/134/12.0
