### ISSUE TITLE
Partner Names Order recalculate losing connection

### ISSUE THREAD

**Issue by source-promo** [OCA/partner-contact#735]
Hi,

I would like to change the partner names order from "lastname firstname" to "Fistname lastname".
Unfortunately when hitting recalculate it takes 10+ minutes and after a while the message pops up "lost connection" and nothing has changed.

I have about 100.000 contacts in my db. 
Is there a way to execute the recalculation with such a big db or any workaround?
Hope you can assist me on this! 

Thanks in advance!

**Comment by pedrobaeza** [comment]
Extend the timeout of your reverse proxy, as this operation takes time.
