### ISSUE TITLE
Personal information page with fields.

### ISSUE THREAD

**Issue by MarkingSC** [OCA/partner-contact#745]
I just tried _partner_contact_personal_information_page_ module, and as it says, it adds the personal information page, but nothing else.

I think is important to set some personal information fields for contact type partners. Many companies need to know personal email address, phone numbers and more from their employees. So, setting personal information fields in _res.partner_ model will avoid to duplicate records refering to the same person.

I propose these fields to add in personal information page:

- street
- street2
- city
- state_id
- zip
- country_id (not sure)
- phone
- mobile
- email

**Comment by pedrobaeza** [comment]
This is not done that way. You have private contacts for that.
