### ISSUE TITLE
Cities did not pull to correct states

### ISSUE THREAD

**Issue by hiltonmw** [OCA/partner-contact#749]
Hi there,

I did my first import from geonames just yesterday and I'm noticing today that many of the cities that have the same name in multiple states did not get imported correctly.  For example, Worcester, the city, resides in MA, NY, PA, and VT.  But upon import, it's placed *ALL* cities named Worcester into VT.  (see screenshots for a few examples)...

![cities_error_1](https://user-images.githubusercontent.com/19822594/59698466-bef3b580-91bd-11e9-9811-6f3a9d83d156.JPG)
![cities_error_2](https://user-images.githubusercontent.com/19822594/59698471-c1eea600-91bd-11e9-8839-77814ae78e53.JPG)

**Comment by pedrobaeza** [comment]
Which Odoo version?

**Comment by hiltonmw** [comment]
Odoo 12, CE

**Comment by hiltonmw** [comment]
any other thoughts on this @pedrobaeza ?

**Comment by pedrobaeza** [comment]
Not right now. I'll check next week when coming from holidays

**Comment by hiltonmw** [comment]
Hi Pedro...

Any updates on this?  I need to build up my production server and I'm concerned this bug will follow me there and I'd like it if it doesn't.  Thanks!

**Comment by hiltonmw** [comment]
For what it's worth, I just spun up a *completely new* instance of Odoo 12 CE - installed the addon/extra and it did the same exact thing.  Ubuntu Server 18.04 x64 with Odoo 12 CE.  All up to date with latest patches/updates/etc.

**Comment by pedrobaeza** [comment]
I come back from holidays tomorrow, and I'll need sometime to find the problem.

**Comment by hiltonmw** [comment]
So sorry to pester, but I'm trying to go live with this and I was wondering if there's been any headway on this.

**Comment by hiltonmw** [comment]
@pedrobaeza - Is there any update on this?  I'm sorry to continue to pester, but without this working properly I'm kind of stuck with setting up my production database, as I don't want to manually input data if it will disrupt your/our troubleshooting in any way...

**Comment by pedrobaeza** [comment]
Sorry but no. This is not top priority for me, and although I confirm there's a bug, I need some free time for checking and solving. I will try this week.

**Comment by davidgonzalezb** [comment]
Hola estoy en México, muy buena aplicación. Odoo 12 Community. Podemos importar todas las Ciudades con el Estado/País. El detalle es al importar Zips. Tenemos diferentes Estados (States) con mismos nombres de Ciudades. Ayudaria tener en Importacion de Zips una columna que incluya State ademas de ZIP / City. Gracias

**Comment by hiltonmw** [comment]
Hi Pedro,

Any luck on a fix for this yet?  Has it always been broken or is there something unique about how it runs now that causes it to break?

Thanks-
-Matt

**Comment by pedrobaeza** [comment]
You can find the fix in #757
