### ISSUE TITLE
Leads screen integration?

### ISSUE THREAD

**Issue by hiltonmw** [OCA/partner-contact#750]
Would it be possible to add this lookup ability to the CRM > Leads screen as well?

Note: I also have an inquiry into Odoo community forum, as it appears you can't even do a contact/customer/company lookup on the leads screen, and for me, that means entering quite a bit more information and duplicating info where I don't need to.

**Comment by pedrobaeza** [comment]
Which ability?

**Comment by hiltonmw** [comment]
Sorry - the "location completion" ability...

**Comment by pedrobaeza** [comment]
https://github.com/OCA/crm/tree/12.0/crm_location
