### ISSUE TITLE
[ADD] partner_brand

### ISSUE THREAD

**Issue by max3903** [OCA/partner-contact#754]
This module allows users to manage brands of the company.

# Usage
* Go to Contacts
* Search the current company
* Click on Edit and add an address
* Check the box "Brand" and enter the brand information: name, logo, address, website, phone

# Technical Specifications

- [x] Add an option "Brand" (brand) in the Type selection list
- [x] Add a filter "Brand" in Contacts
- [ ] Upon creating or saving a brand, check that the parent company and the company of the brand are the same as the company of the connected user.

**Comment by sbidoul** [comment]
@max3903 @pedrobaeza I'm also interested in understanding the relationship of this module to `product_brand`. 

We have a use case for brands but not related to products: ie the same product can be sold under different brands. So the brand will be something to be selected on the SO/Invoice etc.

So I would say a base brand module, unrelated to product, makes sense. And product_brand can depend on it.

WDYT?

**Comment by pedrobaeza** [comment]
OK, but for v12, the dependency should be `product_brand`, but for v13 we can split into `base_brand` (or `brand` only) + `product_brand`.

**Comment by sbidoul** [comment]
cc @sbejaoui, @gva-acsone

**Comment by sbidoul** [comment]
@pedrobaeza @max3903 ok for me with keeping product_brand at least in v12. It does not harm even if we don't set brand on any product.

FYI we are planning the following modules (current list is WIP):

- `brand_sale`: add brand field on SO + filter products proposed by brand
- `brand_account`: 

  - table with optional default receivable account per brand
  - brand field on invoice, proposes default receivable account

- `brand_contract`: brand field on contract, copied when generating invoices
- `brand_contract_sale`: glue module between `brand_sale` and `product_contract`

I'm wondering if we'd need a new repo for that.

We may use [report_subsitute](https://github.com/OCA/reporting-engine/pull/307) to help with generating report (although a different header/footer by brand may be enough).

**Comment by max3903** [comment]
@sbidoul That is a good idea. FYI, you will find:

* `account_brand` in https://github.com/OCA/account-invoicing/issues/564
* `sale_brand` in https://github.com/OCA/sale-workflow/pull/906
* `sale_subscription_brand` in https://github.com/ursais/osi-addons/pull/158

@pedrobaeza `product_brand` was demonstrated to our customer and it does not answer their requirements. They manage different brands that sells the same products and services under the same company. They need the header and footer of the PDF reports to have the brand information: logo, name, address, email, website, phone of the brand, instead of the company one.

**Comment by pedrobaeza** [comment]
But at partner level? That sounds very weird.

**Comment by max3903** [comment]
@pedrobaeza Where would you store the logo, name, address, email, website, phone of the brand?

**Comment by pedrobaeza** [comment]
On a separate model. My point is that you can sell over your different own brands to the same partner. For me this is something more to add to `sale_order_type`, selecting the brand at sales order level (you can have any way a default sales order type for the partner).

Module `sale_order_type_brand`, that takes `product_brand` and `sale_order_type`, and adds a ` brand_id` field on the `sale.order.type` model, and then issue the sales order + invoice with that brand.

**Comment by max3903** [comment]
Why would I create a brand object to store a logo, name, address, email, website and phone when this is already available on `res.partner`???

**Comment by sbidoul** [comment]
@max3903 because a brand is not a partner (in the Object Oriented Programming sense). A brand can have a m2o to a partner to store address and logo.

**Comment by pedrobaeza** [comment]
But the object is already there... you should add the `partner_id` reference in product_brand, not the reverse in my opinion, and that partner will be a children of the partner of the main company.

**Comment by max3903** [comment]
Let's create an issue and converge on version 13 then.

**Comment by sbidoul** [comment]
@max3903 we need it on 12. Do you still have room to adjust the design?

**Comment by max3903** [comment]
Not much. Going live tomorrow...
