### ISSUE TITLE
[12.0] Model 'res.country' does not exist in registry

### ISSUE THREAD

**Issue by josepmy** [OCA/partner-contact#760]
Hi,

I try to import geonames into Odoo and I get this error. All the depencies are checked.

The error throw here:

        # create or retrieve the model's class
        if name in parents:
            if name not in pool:
                raise TypeError("Model %r does not exist in registry." % name)

Aug 04 11:24:16 xxx odoo12[22883]:     force, status, report, loaded_modules, update_module, models_to_check)
Aug 04 11:24:16 xxx odoo12[22883]:   File "/opt/odoo12/odoo/odoo/modules/loading.py", line 313, in load_marked_modules
Aug 04 11:24:16 xxx odoo12[22883]:     perform_checks=perform_checks, models_to_check=models_to_check
Aug 04 11:24:16 xxx odoo12[22883]:   File "/opt/odoo12/odoo/odoo/modules/loading.py", line 188, in load_module_graph
Aug 04 11:24:16 xxx odoo12[22883]:     model_names = registry.load(cr, package)
Aug 04 11:24:16 xxx odoo12[22883]:   File "/opt/odoo12/odoo/odoo/modules/registry.py", line 240, in load
Aug 04 11:24:16 xxx odoo12[22883]:     model = cls._build_model(self, cr)
Aug 04 11:24:16 xxx odoo12[22883]:   File "/opt/odoo12/odoo/odoo/models.py", line 439, in _build_model
Aug 04 11:24:16 xxx odoo12[22883]:     raise TypeError("Model %r does not exist in registry." % name)
Aug 04 11:24:16 xxx odoo12[22883]: TypeError: Model 'res.country' does not exist in registry. - - -

Salut,
Josep M

**Comment by pedrobaeza** [comment]
Incorrect deployment. Nothing to do with the module.

**Comment by josepmy** [comment]
Where can I check the correct deployment?

**Comment by pedrobaeza** [comment]
I suspect you use "Import module" option, which is not valid, but I can't say more.

**Comment by josepmy** [comment]
Yes, I select the country and click import. what is the correct then?

**Comment by pedrobaeza** [comment]
That option doesn't serve.  For nothing except themes. Use regular way for adding addons.

**Comment by josepmy** [comment]
Uninstall and install again from applications?

**Comment by josepmy** [comment]
I uninstall and install and get the same error. What I’m doing wrong?

**Comment by pedrobaeza** [comment]
Copy it to your addons folder, not importing it. This is not the first time you face the same thing.

**Comment by josepmy** [comment]
Copy the ES.zip from geonames into addons? Sorry I’m confused.
