### ISSUE TITLE
[RFC] brand, the path forward

### ISSUE THREAD

**Issue by sbidoul** [OCA/partner-contact#765]
Hi,

We currently have two independent approaches for brands in OCA:
- [partner_brand](https://github.com/OCA/partner-contact/tree/12.0/partner_brand), [account_brand](https://github.com/OCA/account-invoicing/tree/12.0/account_brand), [sale_brand](https://github.com/OCA/sale-workflow/tree/12.0/sale_brand) which basically mark some contacts as being brands and replace company information in report headers/footers with brand information is available
- [product_brand](https://github.com/OCA/product-attribute/tree/12.0/product_brand) which assign products to brand and adds that in some pivot tables

We have more requirements for brand (such as defining receivable/payable accounts by brand, or adding multi-company support on brands) for which neither approach is totally adequate. For that we need a separate `brand` object, since extending `res.partner` will be confusing and will not work in the long run.

So the first step we propose is as follow:
- update `partner_brand` to create a `brand` object with delegation inheritance on `res.partner`, with migration scripts
- update `sale_brand` and `account_brand`, with migration scripts
- add a dedicated menu for brands next to Companies in settings, with dedicated views

This is not perfect, but it's a first step to evolve what is merged today. Further down the road we can consider making `product_brand` depend on this new `brand` model, and possibly replace the delegation inheritance by something else.

@max3903 @pedrobaeza any opinion on this approach?

cc/ @sbejaoui

**Comment by sbejaoui** [comment]
New model res.brand: #766

**Comment by sbejaoui** [comment]
Update for sale_brand [\#920](https://github.com/OCA/sale-workflow/pull/920)

**Comment by sbejaoui** [comment]
Update for account_brand [\#577](https://github.com/OCA/account-invoicing/pull/577)

**Comment by pedrobaeza** [comment]
Should we create a new repo OCA/brand? And about the model name, why `res.brand`?

**Comment by sbejaoui** [comment]
I thought that brands can be seen as system resources and in the same
registry like users, companies, partners, ..

Le ven. 16 août 2019 à 22:28, Pedro M. Baeza <notifications@github.com> a
écrit :

**Comment by max3903** [comment]
Looks like we are doing the same as Odoo: We discuss a topic publicly but internally the decision seems to be already made and the job already done... :)

Anyway, I don't have any strong opinion about where and how the repo/module/object is named/developed. What matters is to maintain the same scope for our current customer. 

If @acsone takes the leadership of maintaining the repo/modules, you can do as you wish. What I would like to know is whether you will take:
* a passive role where we create issues with requirements and designs and submit pull requests that you review
* an active role where we create issues with requirements and we pay you to estimate, design and develop and we review/test.

Thank you.

**Comment by sbidoul** [comment]
> job already done

Eh eh sometimes dev goes faster than I think. Nothing is done, no worries the PRs are up for discussion.

To clarify the context, I created this RFC following design comments that were made by myself and @pedrobaeza on #754. We have additional requirements that make it necessary to evolve the current data model. We think the requirements are generic enough to propose to OCA. 

> What matters is to maintain the same scope for our current customer

What we are proposing do indeed change the datamodel but keep functionality and come with full migration scripts, as well as a longer term roadmap described in this issue, to make it as easy as possible for your customer to migrate. 

I'm mentioning you to get your input in the hope to find a robust design for everyone.

Regarding the passive/active role, and "doing as we wish" I don't understand what you want to say exactly.

**Comment by sbidoul** [comment]
> res.brand

I tend to think the `res` prefix is reserved for Odoo core. Why not simply `brand`?

> new repo OCA/brand

@pedrobaeza a new repo would make sense. Now or for v13? Should it be a new PSC too, or do you think an existing PSC could take it in charge?

**Comment by pedrobaeza** [comment]
If @max3903 agrees, we can do the repo now. As for PSC, I would detach it from other PSCs, as it's very transversal (product, invoicing, sales...).

**Comment by max3903** [comment]
+1 for the new repo

**Comment by NL66278** [comment]
I completely agree with the roadmap and the new repo. One of our customers had its own solution for brands (called sales.channel by them), based on partners with extra attributes. This caused lots of problems. Having a separate brand, or res.brand whatever, model makes much more sense.

**Comment by NL66278** [comment]
As the new repository has been created, and already has the proposed modules, I close this issue here.
