### ISSUE TITLE
[10.0] partner_financial_risk

### ISSUE THREAD

**Issue by WeeDom** [OCA/partner-contact#780]
Hi,

We use partner_financial_risk in a production odoo 10. We're currently exploring upgrading to odoo 12, and we'd like to continue using partner_financial_risk, but you seem to have dropped it as of odoo 11.0.

Has the functionality been moved to a different module in your 12.0 branch?

Thanks
Dominic
Flow Mobile Ltd

**Comment by pedrobaeza** [comment]
https://github.com/OCA/credit-control/tree/12.0/account_financial_risk

**Comment by WeeDom** [comment]
wow! How speedy???
