### ISSUE TITLE
[RFC] Partner License Type and Number

### ISSUE THREAD

**Issue by dreispt** [OCA/partner-contact#799]
Module name: partner_license
Dependency: base
License: AGPL-3

Some regulated businesses need state licenses to be able to operate.
Different locations and different activities (Distribution, Retails, etc.) might have different licenses.

# Configuration

The License Types are configured in the Settings app, menu Technical » Resources » Company License Types.

# Usage

Each license should have it's own Contact record.

In the company's main form, "Add" a Contact, and there the License Type can be selected and the License Number entered. Use an appropriate title in the "Contact Name" field.

In case the same Address has more than one license, a Contact entry needs to be added for each of them.

**Comment by pedrobaeza** [comment]
I think you can use https://github.com/OCA/partner-contact/tree/12.0/partner_identification

**Comment by dreispt** [comment]
Thank you for the suggestion. Indeed that could be used to store license details.
In my use case, the license number and type is required to show in shipping manifests, and needs to be accessible from report templates.
Let me consider if using partner_identification will meet the requirements.

**Comment by NL66278** [comment]
@dreispt If needed you can make a module that builds on partner_identification, like partner_coc.

**Comment by dreispt** [comment]
Yes, that look a nice idea, thank you @NL66278

**Comment by dreispt** [comment]
I'm going ahead with your suggestions, thank you.
