### ISSUE TITLE
[12][base_location_geonames_import] Thread timeout when importing

### ISSUE THREAD

**Issue by raneq** [OCA/partner-contact#829]
Hello!

## Intro

I have had a hard time to import the postal codes for Spain. I could do it for Andorra without issues, but for Spain, some timeouts appeared. However, contrary to what other people found (#598) , my problem wasn't with the reverse proxy, but with the thread timeout.

## Process

It downloads and decompresses the geonames zip in a few seconds, and then starts to import the info inside:
```
2019-12-17 15:47:08,592 22665 INFO odoo
odoo.addons.base_location_geonames_import.wizard.geonames_import:
Starting to create the cities and/or city zip entries 
```

However, after some time, I find this log entry:
```
2019-12-17 15:49:48,939 22665 INFO ?
odoo.service.server:
Thread <Thread(odoo.service.http.request.140675941132032, started 140675941132032)>
virtual real time limit (166/120s) reached. 
```

Crawling the code I found [this config parameter](https://www.odoo.com/documentation/12.0/reference/cmdline.html#cmdoption-odoo-bin-limit-time-real) that effectively defaults to 120.

Increasing it from 2 to 20 minutes, I could complete the import in about 6 and a half minutes, for Spain.

## Question

I don't want to increase 5x the thread timeout, and still risk that somebody will eventually want to import the codes of a larger country and will fail.

I would like to know if there is a better way to leave more time for this specific operation, or if there is margin to optimize the import process so that it doesn't take so long. 

## Details

My server specs (a low-end VPS)
```
$ lscpu
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              1
On-line CPU(s) list: 0
Thread(s) per core:  1
Core(s) per socket:  1
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel Xeon Processor (Skylake, IBRS)
Stepping:            4
CPU MHz:             2099.998
BogoMIPS:            4199.99
...
```

**Comment by pedrobaeza** [comment]
There's no other way. It takes that time for importing such quantity of data.

**Comment by raneq** [comment]
Bad news then. Thank you for your instant reply!
