### ISSUE TITLE
base_location_geonames_import GR.zip not found

### ISSUE THREAD

**Issue by hurrinico** [OCA/partner-contact#831]
I need to import zipcode for greece with geonames.
But [here](http://download.geonames.org/export/zip/) there's no GR.zip file.
I've opened an [issue](http://forum.geonames.org/gforum/posts/list/36080.page#46936) and i've wrote to them.
They responds this:
"Hi Nicola
We are not sure about the license, so we have never added it to the
download.
Best Regards"
How can we move about this?

**Comment by pedrobaeza** [comment]
I'm afraid there's nothing we can do at this side, as the module only try to download what is present at Geonames side.
