### ISSUE TITLE
Feature request - opportunity relationship

### ISSUE THREAD

**Issue by daniel-sjodin** [OCA/partner-contact#847]
We are a company at distribution level and we are often involved in projects where we have multiple companies involved in the same project. There might be an end-user with a need (which will evolve into a project), consultants, integrators and installers. 

It would be a great feature if it was possible to create relationships between organizations and Opportunities or Projects. This way we could track all involvements in a end-user project.

Many thanks
Daniel Sjödin

module: partner_multi_relation
version: 12.0

**Comment by NL66278** [comment]
This seems to me to be more appropiate in the project repository. You might have a look at the project_role module wether it more or less fullfills your requirements.

**Comment by NL66278** [comment]
I close this issue as i has been referred to the appropiate repository.
