### ISSUE TITLE
[13.0] partner_firstname: Tests errors

### ISSUE THREAD

**Issue by rousseldenis** [OCA/partner-contact#851]
13.0 branch is red due to errors in partner_firstname.

I've checked and it could be a commit in core between 28/12/2019 and 23/01/2020.

@lmignon @NL66278

**Comment by NL66278** [comment]
@rousseldenis I do not see much of commits on partner_firstname in this period. Maybe changes in some other piece of Odoo had a side-effect on partner_firstname. I will try to debug the problem.

**Comment by rousseldenis** [comment]
> @rousseldenis I do not see much of commits on partner_firstname in this period. Maybe changes in some other piece of Odoo had a side-effect on partner_firstname. I will try to debug the problem.

Yes, that's what I said. I didn't explore but some commits on Odoo side have been done on that period.

**Comment by rousseldenis** [comment]
@NL66278 I've found the commit that makes travis red:

https://github.com/odoo/odoo/commit/6c99fe3ffec3aeb8d210e3b943ccef81d62d44ce#diff-0a8f125a3f41f36c0507203a63cde9ad

**Comment by rousseldenis** [comment]
See my comment : https://github.com/odoo/odoo/commit/6c99fe3ffec3aeb8d210e3b943ccef81d62d44ce#r37207800

**Comment by NL66278** [comment]
See also this PR, needed to solve the `"Foó bis" != "Foó"` problem in the test of the partner form: https://github.com/odoo/odoo/pull/45355

**Comment by NL66278** [comment]
Downstream PR is here: https://github.com/OCA/OCB/pull/909
