### ISSUE TITLE
[11.0] How to change the default  http://download.geonames.org/export/zip/

### ISSUE THREAD

**Issue by kickfliph** [OCA/partner-contact#903]
Hello everyone,

I'm setting up my Odoo 11 CE and I have installed but not properly configure the module of a particular country I need to pull the Geoname information. I can see the .zip that I'm looking for is located in this path http://download.geonames.org/export/dump/, so how I can have the module pull the information from this path. I have tried adding the entry in General Settings --> Technical --> Parameters --> System Parameters and create a new entry. 
Key    geonames.url 
Value http://download.geonames.org/export/dump/

But it still not working. Please let me know if I missing something else to do or is by another way to reach my gold.

Thanks for all your help.

**Comment by pedrobaeza** [comment]
Nothing to change, just a temporary glitch. Just try again.

**Comment by kickfliph** [comment]
Thanks Pedrobaeza for your quick replay, but I still get the same error :( 

Please let me know if there anything else I can do to resolve this and again thanks for all your help.

![shot-2020-05-10_08-11-51](https://user-images.githubusercontent.com/8335629/81499058-a2a9ad00-9296-11ea-95c9-0fed0dbd8f41.jpg)

**Comment by pedrobaeza** [comment]
Why do you hide your country? Is that a secret? The reason for that should be that your country (whatever it is) is not supported then.

**Comment by kickfliph** [comment]
OOhhh Pedrobaeza thanks again, no secret please accept my apologies, here it is clear. I just wondering because I'm able to do download the .zip and the information in it looks very accurate. 

Thanks Pedrobaeza for all your support.

![shot-2020-05-10_08-31-35](https://user-images.githubusercontent.com/8335629/81499314-b48c4f80-9298-11ea-9c5e-1909cabfd0db.jpg)

**Comment by pedrobaeza** [comment]
Then indeed there's no support for your country. See http://download.geonames.org/export/zip/ for a list of current countries. If you find the file at http://download.geonames.org/export/dump/, it's because there are some raw data, but it's not curated at probably not valid for importing. If you want to inspect and see possible compatibility, you are invited to make a PR about adding the "alternative" path. You will need to change the parser for that alternative, as the data layout is not the same.

**Comment by kickfliph** [comment]
Thanks Pedroobaeza, I'll try to start something here and update it for my country. By the way, on  the README.rst for V11.0 I can see this;

Usage
Go to Settings > Technical > Cities/Locations Management > Import from Geonames, and click on it to open a wizard.

I believe it should be at lease for V11.0;
Usage
Go to General Settings > Technical > Locations Management > Import from Geonames, and click on it to open a wizard.

Please let me know if you agreed,  it will be my pleasure to have it change.

As usual thanks to you also your team you have done an excellent job.

**Comment by pedrobaeza** [comment]
Yeah, it could be that the menu location is not accurate, so if you want to make a PR for changing that, it's also welcome.
