### ISSUE TITLE
[10.0] base_location_geonames_import: Fix url

### ISSUE THREAD

**Issue by rousseldenis** [OCA/partner-contact#905]
Tests are failing since all countries are included in one zip file.

https://github.com/OCA/partner-contact/blob/13.0/base_location_geonames_import/wizard/geonames_import.py#L116

For tests, IMHO we should not rely on external urls. Apart of that, I see they have WebServices, why not using them ?

@pedrobaeza 

EDIT: The base url is now https://download.geonames.org/export/dump/ I'll make a PR for that

**Comment by rousseldenis** [comment]
It seems not to be sufficent as the format appears to have changed too...

**Comment by pedrobaeza** [comment]
As explained in https://github.com/OCA/partner-contact/pull/906#issuecomment-625209511, this is a temporary glitch that Geonames suffers from time to time. The only solution is to wait for the fix, although I know it's an annoyance, it only happens once in 3 months or so, and it takes hours to be restored.

The format in dump doesn't serve, as it doesn't include enough information for all (if I don't remember bad, zipcodes are not expanded). Any way, it can suffer the same from temporary glitches.

Others have suggested to remove the online tests or mock them, but the module is just for importing information from Geonames, so it's totally suitable to test if that download and parsing can be done. If you mock or not tested at all, the important thing is that at the end, the module doesn't serve if you click on import and you get error, or Geonames decides to change the format.

About the webservice, last time I check was a paid service, but maybe that has changed and can be implemented that way. Can you please check?

**Comment by pedrobaeza** [comment]
And Geonames works again perfectly after the less than 1-day glitch...
