### ISSUE TITLE
[12.0] partner_multi_relation - Archive Not Working

### ISSUE THREAD

**Issue by patrickrwilson** [OCA/partner-contact#923]
In the partner_multi_relation module, you are not able to archive relations even though it's an option to do so. I'm assuming this might be because a relation has an inverse record so when you try to archive one, it's not able to because it can't archive both.

Perhaps the archive function should just be removed from the module?

Reproduce:
- In **Contacts**->**Relations**, create a relation
- Select either one or both of the relation records you just created in the list view then go to **actions**->**archive**

**Comment by NL66278** [comment]
An active relation is defined as a relation with no end-date, or an end-date in the future.

So the archiving action should be modified to set the enddate (and the unarchiving to unset it).

**Comment by NL66278** [comment]
Bug is dealt with here: https://github.com/OCA/partner-contact/pull/979
