### ISSUE TITLE
field names

### ISSUE THREAD

**Issue by davidogles** [OCA/partner-contact#925]
In this app, why are the field names not correct? for example you have a field named firstname but the label says "Last Name"
 _inherit = 'res.partner'

    firstname = fields.Char(
        "Last name",
        index=True,
    )
    lastname = fields.Char(
        "First name",
        index=True,

**Comment by NL66278** [comment]
Please point out the file and line in the source code where you see this.

**Comment by davidogles** [comment]
MODEL - res_partner.py
Lines 16 through 22.
thanks,
Dave

**Comment by NL66278** [comment]
I checked all versions of the partner_firstname module from 8.0 to 13.0 and this occurs nowhere. Do you have a very old version? What version (and what commit) are you using?

**Comment by pedrobaeza** [comment]
Closing as no issue. Just use OCA latest source code.

**Comment by davidogles** [comment]
I think I found out what is/has happens.  When you choose to order the name by "lastname firstname" it changes the code in the module.
thanks,
Dave
