### ISSUE TITLE
TypeError: Model 'hr.payslip' does not exist in registry. - - -

### ISSUE THREAD

**Issue by payal-dot** [OCA/partner-contact#926]
i am inheriting payslip module but it's showing not exist issue.
from odoo import models, fields,api

class HrPayslipInherit(models.Model):
	_inherit = 'hr.payslip'
    
	@api.depends('line_ids')
	def _compute_total_salary(self):
		for rec in self:
			total_amount = 0
			for salary_line in rec.line_ids:
				total_amount += salary_line.total
			rec.total_salary = total_amount

	total_salary = fields.Float(compute='_compute_total_salary', string='Net Salary')

<record id="hr_payslip_inherit_tree_view" model="ir.ui.view">
            <field name="model">hr.payslip</field>
            <field name="inherit_id" ref="hr_payroll.view_hr_payslip_tree"/>
            <field name="arch" type="xml">
                <field name="state" position="after">
                    <field name="total_salary"/>
                </field>
            </field>
        </record>
    	
	'depends': ['base','hr_payroll','hr'],

**Comment by skeller1** [comment]
HR Payroll is removed from Odoo13 community Edition.
Inheritance should work for Odoo 12.
