### ISSUE TITLE
Weblate don't synchronize translations, merge conflict

### ISSUE THREAD

**Issue by carlosdauden** [OCA/partner-contact#938]
What is the best way to solve this problem?

https://translation.odoo-community.org/projects/partner-contact-13-0/#history

> First, rewinding head to replay your work on top of it...
> Applying: [IMP] partner_contact_lang: Change language when assigning parent if virtual record
> Using index info to reconstruct a base tree...
> M	partner_contact_lang/README.rst
> M	partner_contact_lang/models/res_partner.py
> M	partner_contact_lang/readme/DESCRIPTION.rst
> M	partner_contact_lang/static/description/index.html
> Falling back to patching base and 3-way merge...
> Auto-merging partner_contact_lang/models/res_partner.py
> CONFLICT (content): Merge conflict in partner_contact_lang/models/res_partner.py
> error: Failed to merge in the changes.
> hint: Use 'git am --show-current-patch' to see the failed patch
> Patch failed at 0001 [IMP] partner_contact_lang: Change language when assigning parent if virtual record
> 
> 

> Resolve all conflicts manually, mark them as resolved with
> "git add/rm <conflicted_files>", then run "git rebase --continue".
> You can instead skip this commit: run "git rebase --skip".
> To abort and get back to the state before "git rebase", run "git rebase --abort".

**Comment by pedrobaeza** [comment]
@sbidoul is there a way to access to weblate internal git repos for doing the rebase and fix the conflicts?

**Comment by pedrobaeza** [comment]
@sbidoul I wonder if you can give a hand here.

**Comment by sbidoul** [comment]
I'll check. There is an easy way but I fear it will lose the latest uncommitted translations. Otherwise it's a painful manual merge.

**Comment by sbidoul** [comment]
I'll probably won't have time today. If someone else with weblate admin rights wants to have a look, it's either

- reset in in repository maintenance: 
![image](https://user-images.githubusercontent.com/692075/88791192-9ba98100-d199-11ea-82e1-e5774fbc4654.png)

- or https://docs.weblate.org/en/weblate-3.11/faq.html#how-to-fix-merge-conflicts-in-translations

**Comment by pedrobaeza** [comment]
Indeed resetting is too hard, as we will lose all the translations made. I don't mind to solve conflicts manually, but not sure if I have the proper rights for accessing the git repository. Let me try and tell you back.

**Comment by pedrobaeza** [comment]
Not sure if someone has reset the changes or fix the conflict, but repo is now clean when I have come to check it, so let's close this. Please review again possible translations.
