### ISSUE TITLE
[13.0] partner_firstname: Wrong company name

### ISSUE THREAD

**Issue by zonclayv** [OCA/partner-contact#964]
### Description of the issue
Contact has wrong name after entering both firstname/lastname for individual and company name.

### Version
Odoo - 13.0 from the odoo repository
partner_firstname - 13.0.1.0.1

### How to reproduce

1. Open contact creating form
2. Switch to individual contact type
3. Enter firstname and lastname e.g. Adam Smith
4. Switch to company contact type
5. Clear name field and enter new name e.g. TestCompany
6. Click on 'Save' button

**Expected result:**
Contact with name 'TestCompany' was created.

**Actual result:**
Contact with name 'Adam Smith' was created.

**Comment by rousseldenis** [comment]
@lmignon @NL66278 Maybe you can help on this ?

**Comment by lmignon** [comment]
@zonclayv Thank you for the report. We've to check and debug to know what's the problem. Unfortunately I've no time at the moment to do it.... I'll try in the coming weeks...
