### ISSUE TITLE
[13.0] partner_firstname: Cannot change internal user firstname and lastname

### ISSUE THREAD

**Issue by zonclayv** [OCA/partner-contact#965]
### Description of the issue
Cannot save user with only lastname filled in, when only firstname was filled in before and vice versa.

### Version
Odoo - 13.0 from the odoo repository
partner_firstname - 13.0.1.0.1

### How to reproduce
1. Create internal user with only with **firstname** field filled (ofc with email/login), lastname - should be empty.
2. Open edit form and clear firstname field and enter new value in **lastname** field
3. Click on 'Save' button

### Expected result:
Internal user with only lastname was saved.

### Actual result:
There is an constraint error occurred, with information that **contact** cannot be saved without name

**Comment by skeller1** [comment]
Hi, tried to fix the problem. Maybe somebody with more ORM inheritance experience could help:

Both models (`res.partner` and `res.users`) are implementing `def _compute_name` (res.users with onchange decorator, res.partner with depends decorator)

Changing the method name in res.users model is wokring and the user record can be stored.
Could somebody explain why res.users model is not "using"  `@api.depends("firstname","lastname") _compute_name(self)` defined in res.partner model (comment out _compute_name method in res.users model before)?
