### ISSUE TITLE
[11.0] partner_multi_relation - add relation identifiers

### ISSUE THREAD

**Issue by benbrich** [OCA/partner-contact#968]
We are having a use case, where it is necessary to save as well the identifiers that partners in a relation give to each other. For example in a supplier/customer relationship the supplier and customer ID's defined for each side by the opponent one.

Now I am not sure if this is a potential improvement for the partner_multi_relation module and if yes, wether it is better to integrate it as an additional option in the relation types or to put it in an dependant e.g. partner_multi_relation_identifiers module?

What's your opinion on this one guys? Thanks for your Input

**Comment by NL66278** [comment]
Hi I think this should go in an new module, as the usecase seems somewhat special to me.
