### ISSUE TITLE
[12.0] partner_multi_relation searching relations other_partner_id

### ISSUE THREAD

**Issue by filipocc** [OCA/partner-contact#983]
Hi!
I'm facing an issue related to this module -> partner_multi_relation
The problem comes when i try to search by "search_relation_partner_id" field (Has relation with). In my case, i have 2 contacts:

- **Partner A**
- **Partner B**

**Partner A** has 2 relations with **Partner B**; in my case, relations could be properties (buildings), so lets say that Partner A has 2 houses:

-  in Partner B address, House 1

-  in Partner B address, House 2

From res.parter.relation.all tree view, i can see both of them, but when i search in res.partner tree view, i have this issue:
-> Performed search retrieves 2 results, but one ID (**Partner B** ID)
![image](https://user-images.githubusercontent.com/15066476/95853213-57b82800-0d55-11eb-927f-8db81f4eddd4.png)
So in my tree view i can only display 1 result even that there are 2 relations. 
Is it possible to display the same ID twice on tree view?  I tried grouping the result but the behaviour is also weird:
![image](https://user-images.githubusercontent.com/15066476/95854293-0a3cba80-0d57-11eb-941b-2edc6335160f.png)
![image](https://user-images.githubusercontent.com/15066476/95854602-75868c80-0d57-11eb-860c-5cf35c7a9ac3.png)

And when i unfold the group, it only displays one record.
![image](https://user-images.githubusercontent.com/15066476/95854990-078e9500-0d58-11eb-928e-4117abcfdd68.png)

Thanks in advance!

**Comment by NL66278** [comment]
Actually you are encountering a bug in the search_count function of Odoo. search_count does not look at the number of unique ids returned from the SQL generated for a search. So if the search finds a record in two ways, it will be counted double. However when doing a normal search, Odoo will only use unique id's.  That explains the results you are seeing. The same with the grouping. The count of 2 shown when the group is collapsed is based an a search_count, when expanded on the actual records shown.

Below a 'manual' SQL, similar to what Odoo is doing for a count, followed by what it should be doing to get the count correct. That is simulating what is done in the _search method of odoo/models.py:
```
odobbrdem12=# select rp.name
 from res_partner rp
 join res_partner_relation_all al on rp.id = al.this_partner_id
 join res_partner op on al.other_partner_id = op.id
 where op.name like 'Bis%';
     name      
---------------
 Jan Boezeroen
 Jan Boezeroen
 Programming
 Helpdesk
(4 rows)

odobbrdem12=# select count(rp.name)
 from res_partner rp
 join res_partner_relation_all al on rp.id = al.this_partner_id
 join res_partner op on al.other_partner_id = op.id
 where op.name like 'Bis%';
 count 
-------
     4
(1 row)

odobbrdem12=# WITH unique_ids AS (
 select distinct rp.id
 from res_partner rp
 join res_partner_relation_all al on rp.id = al.this_partner_id
 join res_partner op on al.other_partner_id = op.id
 where op.name like 'Bis%')
 select count(1) from unique_ids;
 count 
-------
     3
(1 row)
```
